(certificate vampire-megalodon 1
  (problem "vampire-native-certificate")
  (step_proposition "u1" "vampire_or (q) (p)")
  (step_proposition "u2" "vampire_or ((p) -> vampire_false) (r)")
  (step_proposition "u3" "vampire_or ((q) -> vampire_false) (r)")
  (step_proposition "u4" "(r) -> vampire_false")
  (step_proposition "u5" "vampire_or (p) (r)")
  (step_extra "u5" "two_literal" ("selected=~q" "other=q" "selected_parent_index=0" "selected_literal_index=0" "selected_parent_unit=3" "selected_substituted=~q" "selected_substituted_db_indices=~q" "selected_substituted_proposition=(q) -> vampire_false" "other_parent_index=1" "other_literal_index=0" "other_parent_unit=1" "other_substituted=q" "other_substituted_db_indices=q" "other_substituted_proposition=q" "parent_0_substitution=[0 -> X0]" "parent_0_substituted_clause=cnf(u3_subst,axiom,\n    ~q | r).\n" "parent_0_substituted_clause_db_indices=cnf(u3_subst,axiom,\n    ~q | r).\n" "parent_1_substitution=[0 -> X1]" "parent_1_substituted_clause=cnf(u1_subst,axiom,\n    q | p).\n" "parent_1_substituted_clause_db_indices=cnf(u1_subst,axiom,\n    q | p).\n"))
  (step_proposition "u6" "vampire_or (r) (r)")
  (step_extra "u6" "two_literal" ("selected=p" "other=~p" "selected_parent_index=0" "selected_literal_index=0" "selected_parent_unit=5" "selected_substituted=p" "selected_substituted_db_indices=p" "selected_substituted_proposition=p" "other_parent_index=1" "other_literal_index=0" "other_parent_unit=2" "other_substituted=~p" "other_substituted_db_indices=~p" "other_substituted_proposition=(p) -> vampire_false" "parent_0_substitution=[0 -> X0]" "parent_0_substituted_clause=cnf(u5_subst,axiom,\n    p | r).\n" "parent_0_substituted_clause_db_indices=cnf(u5_subst,axiom,\n    p | r).\n" "parent_1_substitution=[0 -> X1]" "parent_1_substituted_clause=cnf(u2_subst,axiom,\n    ~p | r).\n" "parent_1_substituted_clause_db_indices=cnf(u2_subst,axiom,\n    ~p | r).\n"))
  (step_proposition "u7" "r")
  (step_proposition "u8" "vampire_false")
  (step_extra "u8" "two_literal" ("selected=r" "other=~r" "selected_parent_index=0" "selected_literal_index=0" "selected_parent_unit=7" "selected_substituted=r" "selected_substituted_db_indices=r" "selected_substituted_proposition=r" "other_parent_index=1" "other_literal_index=0" "other_parent_unit=4" "other_substituted=~r" "other_substituted_db_indices=~r" "other_substituted_proposition=(r) -> vampire_false" "parent_0_substitution=[0 -> X0]" "parent_0_substituted_clause=cnf(u7_subst,axiom,\n    r).\n" "parent_0_substituted_clause_db_indices=cnf(u7_subst,axiom,\n    r).\n" "parent_1_substitution=[0 -> X1]" "parent_1_substituted_clause=cnf(u4_subst,axiom,\n    ~r).\n" "parent_1_substituted_clause_db_indices=cnf(u4_subst,axiom,\n    ~r).\n"))
  (symbol_declaration "Variable p:prop.")
  (symbol_declaration "Variable q:prop.")
  (symbol_declaration "Variable r:prop.")
  (input "u1" (source axiom "a1") (clause (pos (TMH "q")) (pos (TMH "p"))))
  (input "u2" (source axiom "a2") (clause (neg (TMH "p")) (pos (TMH "r"))))
  (input "u3" (source axiom "a3") (clause (neg (TMH "q")) (pos (TMH "r"))))
  (input "u4" (source axiom "a4") (clause (neg (TMH "r"))))
  (resolve "u5" (parents "u3" "u1") (pivot 0 0) (result (clause (pos (TMH "p")) (pos (TMH "r")))))
  (resolve "u6" (parents "u5" "u2") (pivot 0 0) (result (clause (pos (TMH "r")) (pos (TMH "r")))))
  (factor "u7" (parent "u6") (literals 0 1) (result (clause (pos (TMH "r")))))
  (resolve "u8" (parents "u7" "u4") (pivot 0 0) (result (clause)))
)
