(certificate vampire-megalodon 1
  (problem "core-subsumption-resolution")
  (step_proposition "u1" "vampire_or (q) (p)")
  (step_proposition "u2" "(q) -> vampire_false")
  (step_proposition "u3" "p")
  (step_proposition "u4" "(p) -> vampire_false")
  (step_proposition "u5" "vampire_false")
  (symbol_declaration "Variable p:prop.")
  (symbol_declaration "Variable q:prop.")
  (input "u1" (source axiom "a1") (clause (pos (TMH "q")) (pos (TMH "p"))))
  (input "u2" (source axiom "a2") (clause (neg (TMH "q"))))
  (subsumption_resolution "u3" (parents "u1" "u2") (selected (pos (TMH "q"))) (side_pivot (neg (TMH "q"))) (subst) (result (clause (pos (TMH "p")))))
  (input "u4" (source axiom "a3") (clause (neg (TMH "p"))))
  (resolve "u5" (parents "u3" "u4") (pivot 0 0) (result (clause)))
  (contradiction "u6" "u5")
)
