(certificate vampire-megalodon 1
  (problem "core-factor-long-clause")
  (step_proposition "u1" "vampire_or (p) (vampire_or (q) (q))")
  (step_proposition "u2" "vampire_or (p) (q)")
  (step_proposition "u3" "(p) -> vampire_false")
  (step_proposition "u4" "q")
  (step_proposition "u5" "(q) -> vampire_false")
  (step_proposition "u6" "vampire_false")
  (symbol_declaration "Variable p:prop.")
  (symbol_declaration "Variable q:prop.")
  (input "u1" (source axiom "a1") (clause (pos (TMH "p")) (pos (TMH "q")) (pos (TMH "q"))))
  (factor "u2" (parent "u1") (literals 1 2) (result (clause (pos (TMH "p")) (pos (TMH "q")))))
  (input "u3" (source axiom "a2") (clause (neg (TMH "p"))))
  (resolve "u4" (parents "u2" "u3") (pivot 0 0) (result (clause (pos (TMH "q")))))
  (input "u5" (source axiom "a3") (clause (neg (TMH "q"))))
  (resolve "u6" (parents "u4" "u5") (pivot 0 0) (result (clause)))
  (contradiction "u7" "u6")
)
