(certificate vampire-megalodon 1
  (problem "vampire-native-certificate")
  (step_proposition "u1" "vampire_or (q) (p)")
  (step_proposition "u2" "vampire_or (r) ((p) -> vampire_false)")
  (step_proposition "u3" "vampire_or (s) ((r) -> vampire_false)")
  (step_proposition "u4" "(q) -> vampire_false")
  (step_proposition "u5" "(s) -> vampire_false")
  (step_proposition "u6" "p")
  (step_extra "u6" "two_literal" ("selected=q" "other=~q" "selected_parent_index=0" "selected_literal_index=0" "selected_parent_unit=1" "selected_substituted=q" "selected_substituted_db_indices=q" "selected_substituted_proposition=q" "other_parent_index=1" "other_literal_index=0" "other_parent_unit=4" "other_substituted=~q" "other_substituted_db_indices=~q" "other_substituted_proposition=(q) -> vampire_false" "parent_0_substitution=[0 -> X0]" "parent_0_substituted_clause=cnf(u1_subst,axiom,\n    q | p).\n" "parent_0_substituted_clause_db_indices=cnf(u1_subst,axiom,\n    q | p).\n" "parent_1_substitution=[0 -> X1]" "parent_1_substituted_clause=cnf(u4_subst,axiom,\n    ~q).\n" "parent_1_substituted_clause_db_indices=cnf(u4_subst,axiom,\n    ~q).\n"))
  (step_proposition "u7" "(r) -> vampire_false")
  (step_extra "u7" "two_literal" ("selected=s" "other=~s" "selected_parent_index=0" "selected_literal_index=0" "selected_parent_unit=3" "selected_substituted=s" "selected_substituted_db_indices=s" "selected_substituted_proposition=s" "other_parent_index=1" "other_literal_index=0" "other_parent_unit=5" "other_substituted=~s" "other_substituted_db_indices=~s" "other_substituted_proposition=(s) -> vampire_false" "parent_0_substitution=[0 -> X0]" "parent_0_substituted_clause=cnf(u3_subst,axiom,\n    s | ~r).\n" "parent_0_substituted_clause_db_indices=cnf(u3_subst,axiom,\n    s | ~r).\n" "parent_1_substitution=[0 -> X1]" "parent_1_substituted_clause=cnf(u5_subst,axiom,\n    ~s).\n" "parent_1_substituted_clause_db_indices=cnf(u5_subst,axiom,\n    ~s).\n"))
  (step_proposition "u8" "(p) -> vampire_false")
  (step_extra "u8" "two_literal" ("selected=~r" "other=r" "selected_parent_index=0" "selected_literal_index=0" "selected_parent_unit=7" "selected_substituted=~r" "selected_substituted_db_indices=~r" "selected_substituted_proposition=(r) -> vampire_false" "other_parent_index=1" "other_literal_index=0" "other_parent_unit=2" "other_substituted=r" "other_substituted_db_indices=r" "other_substituted_proposition=r" "parent_0_substitution=[0 -> X0]" "parent_0_substituted_clause=cnf(u7_subst,axiom,\n    ~r).\n" "parent_0_substituted_clause_db_indices=cnf(u7_subst,axiom,\n    ~r).\n" "parent_1_substitution=[0 -> X1]" "parent_1_substituted_clause=cnf(u2_subst,axiom,\n    r | ~p).\n" "parent_1_substituted_clause_db_indices=cnf(u2_subst,axiom,\n    r | ~p).\n"))
  (step_proposition "u9" "vampire_false")
  (step_extra "u9" "two_literal" ("selected=~p" "other=p" "selected_parent_index=0" "selected_literal_index=0" "selected_parent_unit=8" "selected_substituted=~p" "selected_substituted_db_indices=~p" "selected_substituted_proposition=(p) -> vampire_false" "other_parent_index=1" "other_literal_index=0" "other_parent_unit=6" "other_substituted=p" "other_substituted_db_indices=p" "other_substituted_proposition=p" "parent_0_substitution=[0 -> X0]" "parent_0_substituted_clause=cnf(u8_subst,axiom,\n    ~p).\n" "parent_0_substituted_clause_db_indices=cnf(u8_subst,axiom,\n    ~p).\n" "parent_1_substitution=[0 -> X1]" "parent_1_substituted_clause=cnf(u6_subst,axiom,\n    p).\n" "parent_1_substituted_clause_db_indices=cnf(u6_subst,axiom,\n    p).\n"))
  (symbol_declaration "Variable p:prop.")
  (symbol_declaration "Variable q:prop.")
  (symbol_declaration "Variable r:prop.")
  (symbol_declaration "Variable s:prop.")
  (input "u1" (source axiom "a1") (clause (pos (TMH "q")) (pos (TMH "p"))))
  (input "u2" (source axiom "a2") (clause (pos (TMH "r")) (neg (TMH "p"))))
  (input "u3" (source axiom "a3") (clause (pos (TMH "s")) (neg (TMH "r"))))
  (input "u4" (source axiom "a4") (clause (neg (TMH "q"))))
  (input "u5" (source axiom "a5") (clause (neg (TMH "s"))))
  (resolve "u6" (parents "u1" "u4") (pivot 0 0) (result (clause (pos (TMH "p")))))
  (resolve "u7" (parents "u3" "u5") (pivot 0 0) (result (clause (neg (TMH "r")))))
  (resolve "u8" (parents "u7" "u2") (pivot 0 0) (result (clause (neg (TMH "p")))))
  (resolve "u9" (parents "u8" "u6") (pivot 0 0) (result (clause)))
)
