(certificate vampire-megalodon 1
  (problem "core-subsumption-resolution-binary-side")
  (step_proposition "u1" "vampire_or (p) (q)")
  (step_proposition "u2" "vampire_or ((p) -> vampire_false) (q)")
  (step_proposition "u3" "q")
  (step_proposition "u4" "(q) -> vampire_false")
  (step_proposition "u5" "vampire_false")
  (symbol_declaration "Variable p:prop.")
  (symbol_declaration "Variable q:prop.")
  (input "u1" (source axiom "a1") (clause (pos (TMH "p")) (pos (TMH "q"))))
  (input "u2" (source axiom "a2") (clause (neg (TMH "p")) (pos (TMH "q"))))
  (subsumption_resolution "u3" (parents "u1" "u2") (selected (pos (TMH "p"))) (side_pivot (neg (TMH "p"))) (subst) (result (clause (pos (TMH "q")))))
  (input "u4" (source axiom "a3") (clause (neg (TMH "q"))))
  (resolve "u5" (parents "u3" "u4") (pivot 0 0) (result (clause)))
  (contradiction "u6" "u5")
)
