(certificate vampire-megalodon 1
  (problem "vampire-native-certificate")
  (step_proposition "u1" "vampire_or (p) (q)")
  (step_proposition "u2" "vampire_or ((p) -> vampire_false) (q)")
  (step_proposition "u3" "(q) -> vampire_false")
  (step_proposition "u4" "vampire_or (q) (q)")
  (step_extra "u4" "two_literal" ("selected=~p" "other=p" "selected_parent_index=0" "selected_literal_index=0" "selected_parent_unit=2" "selected_substituted=~p" "selected_substituted_db_indices=~p" "selected_substituted_proposition=(p) -> vampire_false" "other_parent_index=1" "other_literal_index=0" "other_parent_unit=1" "other_substituted=p" "other_substituted_db_indices=p" "other_substituted_proposition=p" "parent_0_substitution=[0 -> X0]" "parent_0_substituted_clause=cnf(u2_subst,axiom,\n    ~p | q).\n" "parent_0_substituted_clause_db_indices=cnf(u2_subst,axiom,\n    ~p | q).\n" "parent_1_substitution=[0 -> X1]" "parent_1_substituted_clause=cnf(u1_subst,axiom,\n    p | q).\n" "parent_1_substituted_clause_db_indices=cnf(u1_subst,axiom,\n    p | q).\n"))
  (step_proposition "u5" "q")
  (step_proposition "u6" "vampire_false")
  (step_extra "u6" "two_literal" ("selected=q" "other=~q" "selected_parent_index=0" "selected_literal_index=0" "selected_parent_unit=5" "selected_substituted=q" "selected_substituted_db_indices=q" "selected_substituted_proposition=q" "other_parent_index=1" "other_literal_index=0" "other_parent_unit=3" "other_substituted=~q" "other_substituted_db_indices=~q" "other_substituted_proposition=(q) -> vampire_false" "parent_0_substitution=[0 -> X0]" "parent_0_substituted_clause=cnf(u5_subst,axiom,\n    q).\n" "parent_0_substituted_clause_db_indices=cnf(u5_subst,axiom,\n    q).\n" "parent_1_substitution=[0 -> X1]" "parent_1_substituted_clause=cnf(u3_subst,axiom,\n    ~q).\n" "parent_1_substituted_clause_db_indices=cnf(u3_subst,axiom,\n    ~q).\n"))
  (symbol_declaration "Variable p:prop.")
  (symbol_declaration "Variable q:prop.")
  (input "u1" (source axiom "a1") (clause (pos (TMH "p")) (pos (TMH "q"))))
  (input "u2" (source axiom "a2") (clause (neg (TMH "p")) (pos (TMH "q"))))
  (input "u3" (source axiom "a3") (clause (neg (TMH "q"))))
  (resolve "u4" (parents "u2" "u1") (pivot 0 0) (result (clause (pos (TMH "q")) (pos (TMH "q")))))
  (factor "u5" (parent "u4") (literals 0 1) (result (clause (pos (TMH "q")))))
  (resolve "u6" (parents "u5" "u3") (pivot 0 0) (result (clause)))
)
