(certificate vampire-megalodon 1
  (problem "vampire-native-certificate")
  (step_proposition "u1" "vampire_or (q) (p)")
  (step_proposition "u2" "vampire_or ((q) -> vampire_false) ((p) -> vampire_false)")
  (step_proposition "u3" "vampire_or ((q) -> vampire_false) (p)")
  (step_proposition "u4" "vampire_or (q) ((p) -> vampire_false)")
  (step_proposition "u6" "vampire_or (p) (p)")
  (step_extra "u6" "two_literal" ("selected=~q" "other=q" "selected_parent_index=0" "selected_literal_index=0" "selected_parent_unit=3" "selected_substituted=~q" "selected_substituted_db_indices=~q" "selected_substituted_proposition=(q) -> vampire_false" "other_parent_index=1" "other_literal_index=0" "other_parent_unit=1" "other_substituted=q" "other_substituted_db_indices=q" "other_substituted_proposition=q" "parent_0_substitution=[0 -> X0]" "parent_0_substituted_clause=cnf(u3_subst,axiom,\n    ~q | p).\n" "parent_0_substituted_clause_db_indices=cnf(u3_subst,axiom,\n    ~q | p).\n" "parent_1_substitution=[0 -> X1]" "parent_1_substituted_clause=cnf(u1_subst,axiom,\n    q | p).\n" "parent_1_substituted_clause_db_indices=cnf(u1_subst,axiom,\n    q | p).\n"))
  (step_proposition "u7" "p")
  (step_proposition "u9" "vampire_or ((p) -> vampire_false) ((p) -> vampire_false)")
  (step_extra "u9" "two_literal" ("selected=q" "other=~q" "selected_parent_index=0" "selected_literal_index=0" "selected_parent_unit=4" "selected_substituted=q" "selected_substituted_db_indices=q" "selected_substituted_proposition=q" "other_parent_index=1" "other_literal_index=0" "other_parent_unit=2" "other_substituted=~q" "other_substituted_db_indices=~q" "other_substituted_proposition=(q) -> vampire_false" "parent_0_substitution=[0 -> X0]" "parent_0_substituted_clause=cnf(u4_subst,axiom,\n    q | ~p).\n" "parent_0_substituted_clause_db_indices=cnf(u4_subst,axiom,\n    q | ~p).\n" "parent_1_substitution=[0 -> X1]" "parent_1_substituted_clause=cnf(u2_subst,axiom,\n    ~q | ~p).\n" "parent_1_substituted_clause_db_indices=cnf(u2_subst,axiom,\n    ~q | ~p).\n"))
  (step_proposition "u10" "(p) -> vampire_false")
  (step_proposition "u11" "vampire_false")
  (step_extra "u11" "two_literal" ("selected=~p" "other=p" "selected_parent_index=0" "selected_literal_index=0" "selected_parent_unit=10" "selected_substituted=~p" "selected_substituted_db_indices=~p" "selected_substituted_proposition=(p) -> vampire_false" "other_parent_index=1" "other_literal_index=0" "other_parent_unit=7" "other_substituted=p" "other_substituted_db_indices=p" "other_substituted_proposition=p" "parent_0_substitution=[0 -> X0]" "parent_0_substituted_clause=cnf(u10_subst,axiom,\n    ~p).\n" "parent_0_substituted_clause_db_indices=cnf(u10_subst,axiom,\n    ~p).\n" "parent_1_substitution=[0 -> X1]" "parent_1_substituted_clause=cnf(u7_subst,axiom,\n    p).\n" "parent_1_substituted_clause_db_indices=cnf(u7_subst,axiom,\n    p).\n"))
  (symbol_declaration "Variable p:prop.")
  (symbol_declaration "Variable q:prop.")
  (input "u1" (source axiom "a1") (clause (pos (TMH "q")) (pos (TMH "p"))))
  (input "u2" (source axiom "a2") (clause (neg (TMH "q")) (neg (TMH "p"))))
  (input "u3" (source axiom "a3") (clause (neg (TMH "q")) (pos (TMH "p"))))
  (input "u4" (source axiom "a4") (clause (pos (TMH "q")) (neg (TMH "p"))))
  (resolve "u6" (parents "u3" "u1") (pivot 0 0) (result (clause (pos (TMH "p")) (pos (TMH "p")))))
  (factor "u7" (parent "u6") (literals 0 1) (result (clause (pos (TMH "p")))))
  (resolve "u9" (parents "u4" "u2") (pivot 0 0) (result (clause (neg (TMH "p")) (neg (TMH "p")))))
  (factor "u10" (parent "u9") (literals 0 1) (result (clause (neg (TMH "p")))))
  (resolve "u11" (parents "u10" "u7") (pivot 0 0) (result (clause)))
)
