(certificate vampire-megalodon 1
  (problem "vampire-native-certificate")
  (step_proposition "u29" "In y Y")
  (step_proposition "u30" "Y = Repl (setminus B (Repl (setminus A Y) f)) g")
  (step_extra "u30" "raw" ("number=1"))
  (step_proposition "u31" "In y (Repl (setminus B (Repl (setminus A Y) f)) g)")
  (step_proposition "u32" "(In y (Repl (setminus B (Repl (setminus A Y) f)) g)) -> vampire_false")
  (step_proposition "u84" "In y Y")
  (step_extra "u84" "rectify" ("rule=rectify" "source=In y Y" "target=In y Y" "renaming_count=0"))
  (step_proposition "u85" "vampire_eq_prop (In y Y) (vampire_true)")
  (step_extra "u85" "fool" ("rule=fool elimination" "source=In y Y" "target=vampire_eq_prop (In y Y) (vampire_true)" "pair_0_source=In y Y" "pair_0_target=vampire_eq_prop (In y Y) (vampire_true)"))
  (step_extra "u85" "raw" ("number=1"))
  (step_proposition "u86" "(In y (Repl (setminus B (Repl (setminus A Y) f)) g)) -> vampire_false")
  (step_extra "u86" "rectify" ("rule=rectify" "source=(In y (Repl (setminus B (Repl (setminus A Y) f)) g)) -> vampire_false" "target=(In y (Repl (setminus B (Repl (setminus A Y) f)) g)) -> vampire_false" "renaming_count=0"))
  (step_proposition "u87" "(vampire_eq_prop (In y (Repl (setminus B (Repl (setminus A Y) f)) g)) (vampire_true)) -> vampire_false")
  (step_extra "u87" "fool" ("rule=fool elimination" "source=(In y (Repl (setminus B (Repl (setminus A Y) f)) g)) -> vampire_false" "target=(vampire_eq_prop (In y (Repl (setminus B (Repl (setminus A Y) f)) g)) (vampire_true)) -> vampire_false" "pair_0_source=(In y (Repl (setminus B (Repl (setminus A Y) f)) g)) -> vampire_false" "pair_0_target=(vampire_eq_prop (In y (Repl (setminus B (Repl (setminus A Y) f)) g)) (vampire_true)) -> vampire_false" "pair_1_source=In y (Repl (setminus B (Repl (setminus A Y) f)) g)" "pair_1_target=vampire_eq_prop (In y (Repl (setminus B (Repl (setminus A Y) f)) g)) (vampire_true)"))
  (step_proposition "u88" "(vampire_eq_prop (In y (Repl (setminus B (Repl (setminus A Y) f)) g)) (vampire_true)) -> vampire_false")
  (step_extra "u88" "normal_form" ("rule=flattening" "source=(vampire_eq_prop (In y (Repl (setminus B (Repl (setminus A Y) f)) g)) (vampire_true)) -> vampire_false" "target=(vampire_eq_prop (In y (Repl (setminus B (Repl (setminus A Y) f)) g)) (vampire_true)) -> vampire_false"))
  (step_extra "u88" "raw" ("number=1"))
  (step_proposition "u89" "(vampire_eq_prop (In y (Repl (setminus B (Repl (setminus A Y) f)) g)) (vampire_true)) -> vampire_false")
  (step_extra "u89" "cnf" ("rule=cnf transformation" "parent_unit=88" "parent_kind=formula" "source=(vampire_eq_prop (In y (Repl (setminus B (Repl (setminus A Y) f)) g)) (vampire_true)) -> vampire_false" "source_proposition=(vampire_eq_prop (In y (Repl (setminus B (Repl (setminus A Y) f)) g)) (vampire_true)) -> vampire_false" "target=(vampire_eq_prop (In y (Repl (setminus B (Repl (setminus A Y) f)) g)) (vampire_true)) -> vampire_false" "target_proposition=(vampire_eq_prop (In y (Repl (setminus B (Repl (setminus A Y) f)) g)) (vampire_true)) -> vampire_false" "target_clause=[{\"polarity\":false,\"atom\":{\"eq\":[{\"apply\":[{\"apply\":[{\"const\":\"In\"},{\"const\":\"y\"}]},{\"apply\":[{\"apply\":[{\"const\":\"Repl\"},{\"apply\":[{\"apply\":[{\"const\":\"setminus\"},{\"const\":\"B\"}]},{\"apply\":[{\"apply\":[{\"const\":\"Repl\"},{\"apply\":[{\"apply\":[{\"const\":\"setminus\"},{\"const\":\"A\"}]},{\"const\":\"Y\"}]}]},{\"const\":\"f\"}]}]}]},{\"const\":\"g\"}]}]},{\"const\":\"f__true\"}],\"sort\":\"prop\"}}]" "target_literal_count=1" "target_literal_0=(vampire_eq_prop (In y (Repl (setminus B (Repl (setminus A Y) f)) g)) (vampire_true)) -> vampire_false" "parent_clause_count=1" "clause_parent_unit=88" "clause_index=0" "clause_count=1" "target_variable_sort_count=0"))
  (step_extra "u89" "raw" ("parent=88,index=0,count=1"))
  (step_proposition "u90" "Y = Repl (setminus B (Repl (setminus A Y) f)) g")
  (step_extra "u90" "cnf" ("rule=cnf transformation" "parent_unit=30" "parent_kind=formula" "source=Y = Repl (setminus B (Repl (setminus A Y) f)) g" "source_proposition=Y = Repl (setminus B (Repl (setminus A Y) f)) g" "target=Y = Repl (setminus B (Repl (setminus A Y) f)) g" "target_proposition=Y = Repl (setminus B (Repl (setminus A Y) f)) g" "target_clause=[{\"polarity\":true,\"atom\":{\"eq\":[{\"const\":\"Y\"},{\"apply\":[{\"apply\":[{\"const\":\"Repl\"},{\"apply\":[{\"apply\":[{\"const\":\"setminus\"},{\"const\":\"B\"}]},{\"apply\":[{\"apply\":[{\"const\":\"Repl\"},{\"apply\":[{\"apply\":[{\"const\":\"setminus\"},{\"const\":\"A\"}]},{\"const\":\"Y\"}]}]},{\"const\":\"f\"}]}]}]},{\"const\":\"g\"}]}]}}]" "target_literal_count=1" "target_literal_0=Y = Repl (setminus B (Repl (setminus A Y) f)) g" "parent_clause_count=1" "clause_parent_unit=30" "clause_index=0" "clause_count=1" "target_variable_sort_count=0"))
  (step_extra "u90" "raw" ("parent=30,index=0,count=1"))
  (step_proposition "u94" "vampire_eq_prop (In y Y) (vampire_true)")
  (step_extra "u94" "cnf" ("rule=cnf transformation" "parent_unit=85" "parent_kind=formula" "source=vampire_eq_prop (In y Y) (vampire_true)" "source_proposition=vampire_eq_prop (In y Y) (vampire_true)" "target=vampire_eq_prop (In y Y) (vampire_true)" "target_proposition=vampire_eq_prop (In y Y) (vampire_true)" "target_clause=[{\"polarity\":true,\"atom\":{\"eq\":[{\"apply\":[{\"apply\":[{\"const\":\"In\"},{\"const\":\"y\"}]},{\"const\":\"Y\"}]},{\"const\":\"f__true\"}],\"sort\":\"prop\"}}]" "target_literal_count=1" "target_literal_0=vampire_eq_prop (In y Y) (vampire_true)" "parent_clause_count=1" "clause_parent_unit=85" "clause_index=0" "clause_count=1" "target_variable_sort_count=0"))
  (step_extra "u94" "raw" ("parent=85,index=0,count=1"))
  (step_proposition "u120" "(vampire_eq_prop (In y Y) (vampire_true)) -> vampire_false")
  (step_extra "u120" "rewrite" ("lhs=c_Repl @ (setminus @ c_B @ (c_Repl @ (setminus @ c_A @ c_Y) @ f)) @ g" "target=c_Repl @ (setminus @ c_B @ (c_Repl @ (setminus @ c_A @ c_Y) @ f)) @ g" "rule_lhs=Repl (setminus B (Repl (setminus A Y) f)) g" "redex=Repl (setminus B (Repl (setminus A Y) f)) g" "rule_rhs=Y" "replacement=Y" "rule_lhs=Repl (setminus B (Repl (setminus A Y) f)) g" "rule_rhs=Y" "redex=Repl (setminus B (Repl (setminus A Y) f)) g" "replacement=Y" "parent_0_substitution=[]" "parent_0_substituted_clause=cnf(u89_subst,axiom,\n    (((c_In @ y @ (c_Repl @ (setminus @ c_B @ (c_Repl @ (setminus @ c_A @ c_Y) @ f)) @ g))) != $true)).\n" "parent_0_substituted_clause_db_indices=cnf(u89_subst,axiom,\n    (((c_In @ y @ (c_Repl @ (setminus @ c_B @ (c_Repl @ (setminus @ c_A @ c_Y) @ f)) @ g))) != $true)).\n" "parent_1_substitution=[]" "parent_1_substituted_clause=cnf(u90_subst,axiom,\n    (c_Y = ((c_Repl @ (setminus @ c_B @ (c_Repl @ (setminus @ c_A @ c_Y) @ f)) @ g)))).\n" "parent_1_substituted_clause_db_indices=cnf(u90_subst,axiom,\n    (c_Y = ((c_Repl @ (setminus @ c_B @ (c_Repl @ (setminus @ c_A @ c_Y) @ f)) @ g)))).\n"))
  (step_proposition "u121" "vampire_false")
  (step_extra "u121" "literal" ("selected=(((c_In @ y @ c_Y)) != $true)" "selected_parent_index=0" "selected_literal_index=0" "selected_parent_unit=120" "selected_substitution_source=sat_subsumption" "selected_substitution=[]" "selected_substituted=(((c_In @ y @ c_Y)) != $true)" "selected_substituted_db_indices=(((c_In @ y @ c_Y)) != $true)" "selected_substituted_proposition=(vampire_eq_prop (In y Y) (vampire_true)) -> vampire_false"))
  (symbol_declaration "Variable In:set->set->prop.")
  (symbol_declaration "Variable Repl:set->(set->set)->set.")
  (symbol_declaration "Variable setminus:set->set->set.")
  (symbol_declaration "Variable A:set.")
  (symbol_declaration "Variable B:set.")
  (symbol_declaration "Variable f:set->set.")
  (symbol_declaration "Variable g:set->set.")
  (symbol_declaration "Variable Y:set.")
  (symbol_declaration "Variable y:set.")
  (symbol_declaration "Variable f__true:prop.")
  (formula_input "u29" (source axiom "c_H4") (pos (AP (AP (TMH "In") (TMH "y")) (TMH "Y"))))
  (formula_input "u30" (source axiom "c_H2") (pos (AP (AP (TMH "=") (TMH "Y")) (AP (AP (TMH "Repl") (AP (AP (TMH "setminus") (TMH "B")) (AP (AP (TMH "Repl") (AP (AP (TMH "setminus") (TMH "A")) (TMH "Y"))) (TMH "f")))) (TMH "g")))))
  (formula_input "u31" (source conjecture "conj_c__2Fproject_2Ftmp_2Fsource_5Flinked_5Fstrict_5F100_5Fcorpus_5Ffresh_5F041947_2Fhammer_5F1049_5F20") (pos (AP (AP (TMH "In") (TMH "y")) (AP (AP (TMH "Repl") (AP (AP (TMH "setminus") (TMH "B")) (AP (AP (TMH "Repl") (AP (AP (TMH "setminus") (TMH "A")) (TMH "Y"))) (TMH "f")))) (TMH "g")))))
  (formula_term_input "u32" (source negated_conjecture "conj_c__2Fproject_2Ftmp_2Fsource_5Flinked_5Fstrict_5F100_5Fcorpus_5Ffresh_5F041947_2Fhammer_5F1049_5F20") (formula (IMP (AP (AP (TMH "In") (TMH "y")) (AP (AP (TMH "Repl") (AP (AP (TMH "setminus") (TMH "B")) (AP (AP (TMH "Repl") (AP (AP (TMH "setminus") (TMH "A")) (TMH "Y"))) (TMH "f")))) (TMH "g"))) (TMH "vampire_false"))))
  (rectify_formula "u84" (parent "u29") (result (formula (AP (AP (TMH "In") (TMH "y")) (TMH "Y")))))
  (fool_bool "u85" (parent "u84") (result (pos (AP (AP (TMH "=") (AP (AP (TMH "In") (TMH "y")) (TMH "Y"))) (TMH "f__true")))))
  (rectify_formula "u86" (parent "u32") (result (formula (IMP (AP (AP (TMH "In") (TMH "y")) (AP (AP (TMH "Repl") (AP (AP (TMH "setminus") (TMH "B")) (AP (AP (TMH "Repl") (AP (AP (TMH "setminus") (TMH "A")) (TMH "Y"))) (TMH "f")))) (TMH "g"))) (TMH "vampire_false")))))
  (fool_bool "u87" (parent "u86") (result (neg (AP (AP (TMH "=") (AP (AP (TMH "In") (TMH "y")) (AP (AP (TMH "Repl") (AP (AP (TMH "setminus") (TMH "B")) (AP (AP (TMH "Repl") (AP (AP (TMH "setminus") (TMH "A")) (TMH "Y"))) (TMH "f")))) (TMH "g")))) (TMH "f__true")))))
  (formula_copy "u88" (parent "u87") (result (neg (AP (AP (TMH "=") (AP (AP (TMH "In") (TMH "y")) (AP (AP (TMH "Repl") (AP (AP (TMH "setminus") (TMH "B")) (AP (AP (TMH "Repl") (AP (AP (TMH "setminus") (TMH "A")) (TMH "Y"))) (TMH "f")))) (TMH "g")))) (TMH "f__true")))))
  (cnf_literal "u89" (parent "u88") (result (clause (neg (AP (AP (TMH "=") (AP (AP (TMH "In") (TMH "y")) (AP (AP (TMH "Repl") (AP (AP (TMH "setminus") (TMH "B")) (AP (AP (TMH "Repl") (AP (AP (TMH "setminus") (TMH "A")) (TMH "Y"))) (TMH "f")))) (TMH "g")))) (TMH "f__true"))))))
  (cnf_literal "u90" (parent "u30") (result (clause (pos (AP (AP (TMH "=") (TMH "Y")) (AP (AP (TMH "Repl") (AP (AP (TMH "setminus") (TMH "B")) (AP (AP (TMH "Repl") (AP (AP (TMH "setminus") (TMH "A")) (TMH "Y"))) (TMH "f")))) (TMH "g")))))))
  (cnf_literal "u94" (parent "u85") (result (clause (pos (AP (AP (TMH "=") (AP (AP (TMH "In") (TMH "y")) (TMH "Y"))) (TMH "f__true"))))))
  (equality_symmetry "u120_symmetry" (parent "u90") (literal 0) (result (clause (pos (AP (AP (TMH "=") (AP (AP (TMH "Repl") (AP (AP (TMH "setminus") (TMH "B")) (AP (AP (TMH "Repl") (AP (AP (TMH "setminus") (TMH "A")) (TMH "Y"))) (TMH "f")))) (TMH "g"))) (TMH "Y"))))))
  (paramodulate "u120" (equality "u120_symmetry" 0) (target "u89" 0) (position 0 1 1) (from (AP (AP (TMH "Repl") (AP (AP (TMH "setminus") (TMH "B")) (AP (AP (TMH "Repl") (AP (AP (TMH "setminus") (TMH "A")) (TMH "Y"))) (TMH "f")))) (TMH "g"))) (to (TMH "Y")) (result (clause (neg (AP (AP (TMH "=") (AP (AP (TMH "In") (TMH "y")) (TMH "Y"))) (TMH "f__true"))))))
  (resolve "u121" (parents "u120" "u94") (pivot 0 0) (result (clause)))
)
