(certificate vampire-megalodon 1
  (problem "vampire-native-certificate")
  (step_proposition "u75" "Empty = x")
  (step_extra "u75" "raw" ("number=1"))
  (step_proposition "u80" "Empty = SNoLev x")
  (step_extra "u80" "raw" ("number=1"))
  (step_proposition "u83" "Empty = x")
  (step_proposition "u84" "(Empty = x) -> vampire_false")
  (step_proposition "u242" "(Empty = x) -> vampire_false")
  (step_extra "u242" "normal_form" ("rule=flattening" "source=(Empty = x) -> vampire_false" "target=(Empty = x) -> vampire_false"))
  (step_extra "u242" "raw" ("number=1"))
  (step_proposition "u323" "Empty = x")
  (step_extra "u323" "cnf" ("rule=cnf transformation" "parent_unit=75" "parent_kind=formula" "source=Empty = x" "source_proposition=Empty = x" "target=Empty = x" "target_proposition=Empty = x" "target_clause=[{\"polarity\":true,\"atom\":{\"eq\":[{\"const\":\"Empty\"},{\"const\":\"x\"}]}}]" "target_literal_count=1" "target_literal_0=Empty = x" "parent_clause_count=1" "clause_parent_unit=75" "clause_index=0" "clause_count=1" "target_variable_sort_count=0"))
  (step_extra "u323" "raw" ("parent=75,index=0,count=1"))
  (step_proposition "u332" "Empty = SNoLev x")
  (step_extra "u332" "cnf" ("rule=cnf transformation" "parent_unit=80" "parent_kind=formula" "source=Empty = SNoLev x" "source_proposition=Empty = SNoLev x" "target=Empty = SNoLev x" "target_proposition=Empty = SNoLev x" "target_clause=[{\"polarity\":true,\"atom\":{\"eq\":[{\"const\":\"Empty\"},{\"apply\":[{\"const\":\"SNoLev\"},{\"const\":\"x\"}]}]}}]" "target_literal_count=1" "target_literal_0=Empty = SNoLev x" "parent_clause_count=1" "clause_parent_unit=80" "clause_index=0" "clause_count=1" "target_variable_sort_count=0"))
  (step_extra "u332" "raw" ("parent=80,index=0,count=1"))
  (step_proposition "u335" "(Empty = x) -> vampire_false")
  (step_extra "u335" "cnf" ("rule=cnf transformation" "parent_unit=242" "parent_kind=formula" "source=(Empty = x) -> vampire_false" "source_proposition=(Empty = x) -> vampire_false" "target=(Empty = x) -> vampire_false" "target_proposition=(Empty = x) -> vampire_false" "target_clause=[{\"polarity\":false,\"atom\":{\"eq\":[{\"const\":\"Empty\"},{\"const\":\"x\"}]}}]" "target_literal_count=1" "target_literal_0=(Empty = x) -> vampire_false" "parent_clause_count=1" "clause_parent_unit=242" "clause_index=0" "clause_count=1" "target_variable_sort_count=0"))
  (step_extra "u335" "raw" ("parent=242,index=0,count=1"))
  (step_proposition "u392" "x = SNoLev x")
  (step_extra "u392" "definition_rewrite" ("rule=definition unfolding" "target=x = SNoLev x" "parent_0=Empty = x" "source=Empty = x" "parent_1=Empty = SNoLev x" "definition=Empty = SNoLev x"))
  (step_extra "u392" "raw" ("inlined=[c_Empty]"))
  (step_proposition "u397" "(x = SNoLev x) -> vampire_false")
  (step_extra "u397" "definition_rewrite" ("rule=definition unfolding" "target=(x = SNoLev x) -> vampire_false" "parent_0=(Empty = x) -> vampire_false" "source=(Empty = x) -> vampire_false" "parent_1=Empty = SNoLev x" "definition=Empty = SNoLev x"))
  (step_extra "u397" "raw" ("inlined=[c_Empty]"))
  (step_proposition "u400" "SNoLev x = sF0")
  (step_extra "u400" "function_definition" ("introduced_symbol=sF0" "sort=set" "equality_sort=set" "lhs=SNoLev x" "rhs=sF0" "proposition=SNoLev x = sF0"))
  (step_proposition "u401" "(x = sF0) -> vampire_false")
  (step_extra "u401" "definition_rewrite" ("rule=definition folding" "target=(x = sF0) -> vampire_false" "parent_0=(x = SNoLev x) -> vampire_false" "source=(x = SNoLev x) -> vampire_false" "parent_1=SNoLev x = sF0" "definition=SNoLev x = sF0" "fold_step_count=1" "fold_step_0_lhs=SNoLev x" "fold_step_0_rhs=sF0" "fold_step_0_literal=0" "fold_step_0_position=1"))
  (step_extra "u401" "raw" ("steps=1,step0=(c_SNoLev @ x -> sF0)@0:1"))
  (step_proposition "u421" "x = sF0")
  (step_extra "u421" "rewrite" ("lhs=c_SNoLev @ x" "target=c_SNoLev @ x" "rule_lhs=SNoLev x" "redex=SNoLev x" "rule_rhs=x" "replacement=x" "rule_lhs=SNoLev x" "rule_rhs=x" "redex=SNoLev x" "replacement=x" "parent_0_substitution=[]" "parent_0_substituted_clause=cnf(u400_subst,axiom,\n    (((c_SNoLev @ x)) = sF0)).\n" "parent_0_substituted_clause_db_indices=cnf(u400_subst,axiom,\n    (((c_SNoLev @ x)) = sF0)).\n" "parent_1_substitution=[]" "parent_1_substituted_clause=cnf(u392_subst,axiom,\n    (x = ((c_SNoLev @ x)))).\n" "parent_1_substituted_clause_db_indices=cnf(u392_subst,axiom,\n    (x = ((c_SNoLev @ x)))).\n"))
  (step_proposition "u422" "vampire_false")
  (step_extra "u422" "literal" ("selected=(x = sF0)" "selected_parent_index=0" "selected_literal_index=0" "selected_parent_unit=421" "selected_substitution_source=sat_subsumption" "selected_substitution=[]" "selected_substituted=(x = sF0)" "selected_substituted_db_indices=(x = sF0)" "selected_substituted_proposition=x = sF0"))
  (symbol_declaration "Variable Empty:set.")
  (symbol_declaration "Variable SNoLev:set->set.")
  (symbol_declaration "Variable x:set.")
  (symbol_declaration "Variable sF0:set.")
  (formula_input "u75" (source axiom "c_L1") (pos (AP (AP (TMH "=") (TMH "Empty")) (TMH "x"))))
  (formula_input "u80" (source axiom "c_Hx2") (pos (AP (AP (TMH "=") (TMH "Empty")) (AP (TMH "SNoLev") (TMH "x")))))
  (formula_input "u83" (source conjecture "conj_c__2Fproject_2Ftmp_2Fsource_5Flinked_5Fstrict_5F100_5Fcorpus_5Ffresh_5F041947_2Fhammer_5F11578_5F57") (pos (AP (AP (TMH "=") (TMH "Empty")) (TMH "x"))))
  (formula_term_input "u84" (source negated_conjecture "conj_c__2Fproject_2Ftmp_2Fsource_5Flinked_5Fstrict_5F100_5Fcorpus_5Ffresh_5F041947_2Fhammer_5F11578_5F57") (formula (IMP (AP (AP (TMH "=") (TMH "Empty")) (TMH "x")) (TMH "vampire_false"))))
  (formula_copy "u242" (parent "u84") (result (neg (AP (AP (TMH "=") (TMH "Empty")) (TMH "x")))))
  (cnf_literal "u323" (parent "u75") (result (clause (pos (AP (AP (TMH "=") (TMH "Empty")) (TMH "x"))))))
  (cnf_literal "u332" (parent "u80") (result (clause (pos (AP (AP (TMH "=") (TMH "Empty")) (AP (TMH "SNoLev") (TMH "x")))))))
  (cnf_literal "u335" (parent "u242") (result (clause (neg (AP (AP (TMH "=") (TMH "Empty")) (TMH "x"))))))
  (paramodulate "u392" (equality "u332" 0) (target "u323" 0) (position 0 1) (from (TMH "Empty")) (to (AP (TMH "SNoLev") (TMH "x"))) (result (clause (pos (AP (AP (TMH "=") (TMH "x")) (AP (TMH "SNoLev") (TMH "x")))))))
  (paramodulate "u397" (equality "u332" 0) (target "u335" 0) (position 0 1) (from (TMH "Empty")) (to (AP (TMH "SNoLev") (TMH "x"))) (result (clause (neg (AP (AP (TMH "=") (TMH "x")) (AP (TMH "SNoLev") (TMH "x")))))))
  (definition_input "u400" (result (clause (pos (AP (AP (TMH "=") (AP (TMH "SNoLev") (TMH "x"))) (TMH "sF0"))))))
  (paramodulate "u401" (equality "u400" 0) (target "u397" 0) (position 1) (from (AP (TMH "SNoLev") (TMH "x"))) (to (TMH "sF0")) (result (clause (neg (AP (AP (TMH "=") (TMH "x")) (TMH "sF0"))))))
  (equality_symmetry "u421_symmetry" (parent "u392") (literal 0) (result (clause (pos (AP (AP (TMH "=") (AP (TMH "SNoLev") (TMH "x"))) (TMH "x"))))))
  (paramodulate "u421" (equality "u421_symmetry" 0) (target "u400" 0) (position 0 1) (from (AP (TMH "SNoLev") (TMH "x"))) (to (TMH "x")) (result (clause (pos (AP (AP (TMH "=") (TMH "x")) (TMH "sF0"))))))
  (resolve "u422" (parents "u421" "u401") (pivot 0 0) (result (clause)))
)
