(certificate vampire-megalodon 1
  (problem "vampire-native-certificate")
  (step_proposition "u71" "m = add_SNo (mul_SNo q n) r")
  (step_extra "u71" "raw" ("number=1"))
  (step_proposition "u91" "minus_SNo m = minus_SNo (add_SNo (mul_SNo q n) r)")
  (step_proposition "u92" "(minus_SNo m = minus_SNo (add_SNo (mul_SNo q n) r)) -> vampire_false")
  (step_proposition "u267" "(minus_SNo m = minus_SNo (add_SNo (mul_SNo q n) r)) -> vampire_false")
  (step_extra "u267" "normal_form" ("rule=flattening" "source=(minus_SNo m = minus_SNo (add_SNo (mul_SNo q n) r)) -> vampire_false" "target=(minus_SNo m = minus_SNo (add_SNo (mul_SNo q n) r)) -> vampire_false"))
  (step_extra "u267" "raw" ("number=1"))
  (step_proposition "u283" "(minus_SNo m = minus_SNo (add_SNo (mul_SNo q n) r)) -> vampire_false")
  (step_extra "u283" "cnf" ("rule=cnf transformation" "parent_unit=267" "parent_kind=formula" "source=(minus_SNo m = minus_SNo (add_SNo (mul_SNo q n) r)) -> vampire_false" "source_proposition=(minus_SNo m = minus_SNo (add_SNo (mul_SNo q n) r)) -> vampire_false" "target=(minus_SNo m = minus_SNo (add_SNo (mul_SNo q n) r)) -> vampire_false" "target_proposition=(minus_SNo m = minus_SNo (add_SNo (mul_SNo q n) r)) -> vampire_false" "target_clause=[{\"polarity\":false,\"atom\":{\"eq\":[{\"apply\":[{\"const\":\"minus_SNo\"},{\"const\":\"m\"}]},{\"apply\":[{\"const\":\"minus_SNo\"},{\"apply\":[{\"apply\":[{\"const\":\"add_SNo\"},{\"apply\":[{\"apply\":[{\"const\":\"mul_SNo\"},{\"const\":\"q\"}]},{\"const\":\"n\"}]}]},{\"const\":\"r\"}]}]}]}}]" "target_literal_count=1" "target_literal_0=(minus_SNo m = minus_SNo (add_SNo (mul_SNo q n) r)) -> vampire_false" "parent_clause_count=1" "clause_parent_unit=267" "clause_index=0" "clause_count=1" "target_variable_sort_count=0"))
  (step_extra "u283" "raw" ("parent=267,index=0,count=1"))
  (step_proposition "u286" "m = add_SNo (mul_SNo q n) r")
  (step_extra "u286" "cnf" ("rule=cnf transformation" "parent_unit=71" "parent_kind=formula" "source=m = add_SNo (mul_SNo q n) r" "source_proposition=m = add_SNo (mul_SNo q n) r" "target=m = add_SNo (mul_SNo q n) r" "target_proposition=m = add_SNo (mul_SNo q n) r" "target_clause=[{\"polarity\":true,\"atom\":{\"eq\":[{\"const\":\"m\"},{\"apply\":[{\"apply\":[{\"const\":\"add_SNo\"},{\"apply\":[{\"apply\":[{\"const\":\"mul_SNo\"},{\"const\":\"q\"}]},{\"const\":\"n\"}]}]},{\"const\":\"r\"}]}]}}]" "target_literal_count=1" "target_literal_0=m = add_SNo (mul_SNo q n) r" "parent_clause_count=1" "clause_parent_unit=71" "clause_index=0" "clause_count=1" "target_variable_sort_count=0"))
  (step_extra "u286" "raw" ("parent=71,index=0,count=1"))
  (step_proposition "u319" "(minus_SNo m = minus_SNo m) -> vampire_false")
  (step_extra "u319" "rewrite" ("lhs=add_5FSNo @ (mul_5FSNo @ q @ n) @ r" "target=add_5FSNo @ (mul_5FSNo @ q @ n) @ r" "rule_lhs=add_SNo (mul_SNo q n) r" "redex=add_SNo (mul_SNo q n) r" "rule_rhs=m" "replacement=m" "rule_lhs=add_SNo (mul_SNo q n) r" "rule_rhs=m" "redex=add_SNo (mul_SNo q n) r" "replacement=m" "parent_0_substitution=[]" "parent_0_substituted_clause=cnf(u283_subst,axiom,\n    (((minus_5FSNo @ m)) != ((minus_5FSNo @ (add_5FSNo @ (mul_5FSNo @ q @ n) @ r))))).\n" "parent_0_substituted_clause_db_indices=cnf(u283_subst,axiom,\n    (((minus_5FSNo @ m)) != ((minus_5FSNo @ (add_5FSNo @ (mul_5FSNo @ q @ n) @ r))))).\n" "parent_1_substitution=[]" "parent_1_substituted_clause=cnf(u286_subst,axiom,\n    (m = ((add_5FSNo @ (mul_5FSNo @ q @ n) @ r)))).\n" "parent_1_substituted_clause_db_indices=cnf(u286_subst,axiom,\n    (m = ((add_5FSNo @ (mul_5FSNo @ q @ n) @ r)))).\n"))
  (step_proposition "u320" "vampire_false")
  (symbol_declaration "Variable minus_SNo:set->set.")
  (symbol_declaration "Variable add_SNo:set->set->set.")
  (symbol_declaration "Variable mul_SNo:set->set->set.")
  (symbol_declaration "Variable n:set.")
  (symbol_declaration "Variable m:set.")
  (symbol_declaration "Variable q:set.")
  (symbol_declaration "Variable r:set.")
  (formula_input "u71" (source axiom "c_L2") (pos (AP (AP (TMH "=") (TMH "m")) (AP (AP (TMH "add_SNo") (AP (AP (TMH "mul_SNo") (TMH "q")) (TMH "n"))) (TMH "r")))))
  (formula_input "u91" (source conjecture "conj_c__2Fproject_2Ftmp_2Fsource_5Flinked_5Fstrict_5F100_5Fcorpus_5Ffresh_5F041947_2Fhammer_5F10823_5F92") (pos (AP (AP (TMH "=") (AP (TMH "minus_SNo") (TMH "m"))) (AP (TMH "minus_SNo") (AP (AP (TMH "add_SNo") (AP (AP (TMH "mul_SNo") (TMH "q")) (TMH "n"))) (TMH "r"))))))
  (formula_term_input "u92" (source negated_conjecture "conj_c__2Fproject_2Ftmp_2Fsource_5Flinked_5Fstrict_5F100_5Fcorpus_5Ffresh_5F041947_2Fhammer_5F10823_5F92") (formula (IMP (AP (AP (TMH "=") (AP (TMH "minus_SNo") (TMH "m"))) (AP (TMH "minus_SNo") (AP (AP (TMH "add_SNo") (AP (AP (TMH "mul_SNo") (TMH "q")) (TMH "n"))) (TMH "r")))) (TMH "vampire_false"))))
  (formula_copy "u267" (parent "u92") (result (neg (AP (AP (TMH "=") (AP (TMH "minus_SNo") (TMH "m"))) (AP (TMH "minus_SNo") (AP (AP (TMH "add_SNo") (AP (AP (TMH "mul_SNo") (TMH "q")) (TMH "n"))) (TMH "r")))))))
  (cnf_literal "u283" (parent "u267") (result (clause (neg (AP (AP (TMH "=") (AP (TMH "minus_SNo") (TMH "m"))) (AP (TMH "minus_SNo") (AP (AP (TMH "add_SNo") (AP (AP (TMH "mul_SNo") (TMH "q")) (TMH "n"))) (TMH "r"))))))))
  (cnf_literal "u286" (parent "u71") (result (clause (pos (AP (AP (TMH "=") (TMH "m")) (AP (AP (TMH "add_SNo") (AP (AP (TMH "mul_SNo") (TMH "q")) (TMH "n"))) (TMH "r")))))))
  (equality_symmetry "u319_symmetry" (parent "u286") (literal 0) (result (clause (pos (AP (AP (TMH "=") (AP (AP (TMH "add_SNo") (AP (AP (TMH "mul_SNo") (TMH "q")) (TMH "n"))) (TMH "r"))) (TMH "m"))))))
  (paramodulate "u319" (equality "u319_symmetry" 0) (target "u283" 0) (position 1 1) (from (AP (AP (TMH "add_SNo") (AP (AP (TMH "mul_SNo") (TMH "q")) (TMH "n"))) (TMH "r"))) (to (TMH "m")) (result (clause (neg (AP (AP (TMH "=") (AP (TMH "minus_SNo") (TMH "m"))) (AP (TMH "minus_SNo") (TMH "m")))))))
  (equality_resolution "u320" (parent "u319") (literal 0) (result (clause)))
)
