(certificate vampire-megalodon 1
  (problem "vampire-native-certificate")
  (step_proposition "u68" "forall X0:set, In X0 int -> SNo X0")
  (step_variable_sorts "u68" ("X0:set"))
  (step_proposition "u77" "In n int")
  (step_proposition "u78" "SNo n")
  (step_proposition "u79" "(SNo n) -> vampire_false")
  (step_proposition "u212" "forall X0:set, In X0 int -> SNo X0")
  (step_variable_sorts "u212" ("X0:set"))
  (step_extra "u212" "rectify" ("rule=rectify" "source=forall X0:set, In X0 int -> SNo X0" "target=forall X0:set, In X0 int -> SNo X0" "renaming_count=1" "renaming_0_source=forall X0:set, In X0 int -> SNo X0" "renaming_0_source_substituted=forall X0:set, In X0 int -> SNo X0" "renaming_0_target=forall X0:set, In X0 int -> SNo X0"))
  (step_proposition "u213" "forall X0:set, vampire_eq_prop (In X0 int) (vampire_true) -> vampire_eq_prop (SNo X0) (vampire_true)")
  (step_variable_sorts "u213" ("X0:set"))
  (step_extra "u213" "fool" ("rule=fool elimination" "source=forall X0:set, In X0 int -> SNo X0" "target=forall X0:set, vampire_eq_prop (In X0 int) (vampire_true) -> vampire_eq_prop (SNo X0) (vampire_true)" "pair_0_source=forall X0:set, In X0 int -> SNo X0" "pair_0_target=forall X0:set, vampire_eq_prop (In X0 int) (vampire_true) -> vampire_eq_prop (SNo X0) (vampire_true)" "pair_1_source=In X0 int -> SNo X0" "pair_1_target=vampire_eq_prop (In X0 int) (vampire_true) -> vampire_eq_prop (SNo X0) (vampire_true)" "pair_2_source=In X0 int" "pair_2_target=vampire_eq_prop (In X0 int) (vampire_true)" "pair_3_source=SNo X0" "pair_3_target=vampire_eq_prop (SNo X0) (vampire_true)"))
  (step_proposition "u230" "In n int")
  (step_extra "u230" "rectify" ("rule=rectify" "source=In n int" "target=In n int" "renaming_count=0"))
  (step_proposition "u231" "vampire_eq_prop (In n int) (vampire_true)")
  (step_extra "u231" "fool" ("rule=fool elimination" "source=In n int" "target=vampire_eq_prop (In n int) (vampire_true)" "pair_0_source=In n int" "pair_0_target=vampire_eq_prop (In n int) (vampire_true)"))
  (step_extra "u231" "raw" ("number=1"))
  (step_proposition "u232" "(SNo n) -> vampire_false")
  (step_extra "u232" "rectify" ("rule=rectify" "source=(SNo n) -> vampire_false" "target=(SNo n) -> vampire_false" "renaming_count=0"))
  (step_proposition "u233" "(vampire_eq_prop (SNo n) (vampire_true)) -> vampire_false")
  (step_extra "u233" "fool" ("rule=fool elimination" "source=(SNo n) -> vampire_false" "target=(vampire_eq_prop (SNo n) (vampire_true)) -> vampire_false" "pair_0_source=(SNo n) -> vampire_false" "pair_0_target=(vampire_eq_prop (SNo n) (vampire_true)) -> vampire_false" "pair_1_source=SNo n" "pair_1_target=vampire_eq_prop (SNo n) (vampire_true)"))
  (step_proposition "u234" "(vampire_eq_prop (SNo n) (vampire_true)) -> vampire_false")
  (step_extra "u234" "normal_form" ("rule=flattening" "source=(vampire_eq_prop (SNo n) (vampire_true)) -> vampire_false" "target=(vampire_eq_prop (SNo n) (vampire_true)) -> vampire_false"))
  (step_extra "u234" "raw" ("number=1"))
  (step_proposition "u235" "forall X0:set, vampire_or ((vampire_eq_prop (In X0 int) (vampire_true)) -> vampire_false) (vampire_eq_prop (SNo X0) (vampire_true))")
  (step_variable_sorts "u235" ("X0:set"))
  (step_extra "u235" "normal_form" ("rule=ennf transformation" "source=forall X0:set, vampire_eq_prop (In X0 int) (vampire_true) -> vampire_eq_prop (SNo X0) (vampire_true)" "target=forall X0:set, vampire_or ((vampire_eq_prop (In X0 int) (vampire_true)) -> vampire_false) (vampire_eq_prop (SNo X0) (vampire_true))" "pair_0_source=forall X0:set, vampire_eq_prop (In X0 int) (vampire_true) -> vampire_eq_prop (SNo X0) (vampire_true)" "pair_0_target=forall X0:set, vampire_or ((vampire_eq_prop (In X0 int) (vampire_true)) -> vampire_false) (vampire_eq_prop (SNo X0) (vampire_true))" "pair_0_path=root" "pair_1_source=vampire_eq_prop (In X0 int) (vampire_true) -> vampire_eq_prop (SNo X0) (vampire_true)" "pair_1_target=vampire_or ((vampire_eq_prop (In X0 int) (vampire_true)) -> vampire_false) (vampire_eq_prop (SNo X0) (vampire_true))" "pair_1_path=root.body" "pair_2_source=vampire_eq_prop (In X0 int) (vampire_true) -> false" "pair_2_target=(vampire_eq_prop (In X0 int) (vampire_true)) -> vampire_false" "pair_2_path=root.body.ennf_imp_left"))
  (step_extra "u235" "raw" ("number=1"))
  (step_proposition "u236" "(vampire_eq_prop (SNo n) (vampire_true)) -> vampire_false")
  (step_extra "u236" "cnf" ("rule=cnf transformation" "parent_unit=234" "parent_kind=formula" "source=(vampire_eq_prop (SNo n) (vampire_true)) -> vampire_false" "source_proposition=(vampire_eq_prop (SNo n) (vampire_true)) -> vampire_false" "target=(vampire_eq_prop (SNo n) (vampire_true)) -> vampire_false" "target_proposition=(vampire_eq_prop (SNo n) (vampire_true)) -> vampire_false" "target_clause=[{\"polarity\":false,\"atom\":{\"eq\":[{\"apply\":[{\"const\":\"SNo\"},{\"const\":\"n\"}]},{\"const\":\"f__true\"}],\"sort\":\"prop\"}}]" "target_literal_count=1" "target_literal_0=(vampire_eq_prop (SNo n) (vampire_true)) -> vampire_false" "parent_clause_count=1" "clause_parent_unit=234" "clause_index=0" "clause_count=1" "target_variable_sort_count=0"))
  (step_extra "u236" "raw" ("parent=234,index=0,count=1"))
  (step_proposition "u237" "vampire_eq_prop (In n int) (vampire_true)")
  (step_extra "u237" "cnf" ("rule=cnf transformation" "parent_unit=231" "parent_kind=formula" "source=vampire_eq_prop (In n int) (vampire_true)" "source_proposition=vampire_eq_prop (In n int) (vampire_true)" "target=vampire_eq_prop (In n int) (vampire_true)" "target_proposition=vampire_eq_prop (In n int) (vampire_true)" "target_clause=[{\"polarity\":true,\"atom\":{\"eq\":[{\"apply\":[{\"apply\":[{\"const\":\"In\"},{\"const\":\"n\"}]},{\"const\":\"int\"}]},{\"const\":\"f__true\"}],\"sort\":\"prop\"}}]" "target_literal_count=1" "target_literal_0=vampire_eq_prop (In n int) (vampire_true)" "parent_clause_count=1" "clause_parent_unit=231" "clause_index=0" "clause_count=1" "target_variable_sort_count=0"))
  (step_extra "u237" "raw" ("parent=231,index=0,count=1"))
  (step_proposition "u238" "forall X0:set, vampire_or ((vampire_eq_prop (In X0 int) (vampire_true)) -> vampire_false) (vampire_eq_prop (SNo X0) (vampire_true))")
  (step_variable_sorts "u238" ("X0:set"))
  (step_extra "u238" "cnf" ("rule=cnf transformation" "parent_unit=235" "parent_kind=formula" "source=forall X0:set, vampire_or ((vampire_eq_prop (In X0 int) (vampire_true)) -> vampire_false) (vampire_eq_prop (SNo X0) (vampire_true))" "source_proposition=forall X0:set, vampire_or ((vampire_eq_prop (In X0 int) (vampire_true)) -> vampire_false) (vampire_eq_prop (SNo X0) (vampire_true))" "target=forall X0:set, vampire_or ((vampire_eq_prop (In X0 int) (vampire_true)) -> vampire_false) (vampire_eq_prop (SNo X0) (vampire_true))" "target_proposition=forall X0:set, vampire_or ((vampire_eq_prop (In X0 int) (vampire_true)) -> vampire_false) (vampire_eq_prop (SNo X0) (vampire_true))" "target_clause=[{\"polarity\":false,\"atom\":{\"eq\":[{\"apply\":[{\"apply\":[{\"const\":\"In\"},{\"var\":\"X0\"}]},{\"const\":\"int\"}]},{\"const\":\"f__true\"}],\"sort\":\"prop\"}},{\"polarity\":true,\"atom\":{\"eq\":[{\"apply\":[{\"const\":\"SNo\"},{\"var\":\"X0\"}]},{\"const\":\"f__true\"}],\"sort\":\"prop\"}}]" "target_literal_count=2" "target_literal_0=(vampire_eq_prop (In X0 int) (vampire_true)) -> vampire_false" "target_literal_1=vampire_eq_prop (SNo X0) (vampire_true)" "parent_clause_count=1" "clause_parent_unit=235" "clause_index=0" "clause_count=1" "target_variable_sort_count=1" "target_variable_sort_0=X0:set"))
  (step_extra "u238" "raw" ("parent=235,index=0,count=1"))
  (step_proposition "u240" "forall X0:prop, vampire_or (vampire_eq_prop (vampire_true) (X0)) (vampire_eq_prop (vampire_false) (X0))")
  (step_variable_sorts "u240" ("X0:prop"))
  (step_proposition "u243" "vampire_or ((vampire_eq_prop (vampire_true) (vampire_true)) -> vampire_false) (vampire_eq_prop (SNo n) (vampire_false))")
  (step_extra "u243" "two_literal_rewrite" ("selected=(((c_SNo @ n)) != $true)" "other=($true = X0)" "selected_parent_index=0" "selected_literal_index=0" "selected_parent_unit=236" "selected_substituted=(((c_SNo @ n)) != $true)" "selected_substituted_db_indices=(((c_SNo @ n)) != $true)" "selected_substituted_proposition=(vampire_eq_prop (SNo n) (vampire_true)) -> vampire_false" "other_parent_index=1" "other_literal_index=0" "other_parent_unit=240" "other_substituted=(((c_SNo @ n)) = $true)" "other_substituted_db_indices=(((c_SNo @ n)) = $true)" "other_substituted_proposition=vampire_eq_prop (SNo n) (vampire_true)" "lhs=X0" "target=c_SNo @ n" "lhs_term=X0" "target_term=SNo n" "target_sort=prop" "parent_0_substitution=[0 -> X0]" "parent_0_substituted_clause=cnf(u236_subst,axiom,\n    (((c_SNo @ n)) != $true)).\n" "parent_0_substituted_clause_db_indices=cnf(u236_subst,axiom,\n    (((c_SNo @ n)) != $true)).\n" "parent_1_substitution=[0 -> c_SNo @ n]" "parent_1_substituted_clause=cnf(u240_subst,axiom,\n    (((c_SNo @ n)) = $true) | (((c_SNo @ n)) = $false)).\n" "parent_1_substituted_clause_db_indices=cnf(u240_subst,axiom,\n    (((c_SNo @ n)) = $true) | (((c_SNo @ n)) = $false)).\n"))
  (step_proposition "u245" "vampire_eq_prop (SNo n) (vampire_false)")
  (step_proposition "u291" "vampire_or ((vampire_eq_prop (vampire_true) (vampire_true)) -> vampire_false) (vampire_eq_prop (SNo n) (vampire_true))")
  (step_extra "u291" "two_literal_rewrite" ("selected=(((c_In @ X0 @ int)) != $true)" "other=(((c_In @ n @ int)) = $true)" "selected_parent_index=0" "selected_literal_index=0" "selected_parent_unit=238" "selected_substituted=(((c_In @ n @ int)) != $true)" "selected_substituted_db_indices=(((c_In @ n @ int)) != $true)" "selected_substituted_proposition=(vampire_eq_prop (In n int) (vampire_true)) -> vampire_false" "other_parent_index=1" "other_literal_index=0" "other_parent_unit=237" "other_substituted=(((c_In @ n @ int)) = $true)" "other_substituted_db_indices=(((c_In @ n @ int)) = $true)" "other_substituted_proposition=vampire_eq_prop (In n int) (vampire_true)" "lhs=c_In @ n @ int" "target=c_In @ X0 @ int" "lhs_term=In n int" "target_term=In X0 int" "lhs_sort=prop" "target_sort=prop" "parent_0_substitution=[0 -> n]" "parent_0_substituted_clause=cnf(u238_subst,axiom,\n    (((c_In @ n @ int)) != $true) | (((c_SNo @ n)) = $true)).\n" "parent_0_substituted_clause_db_indices=cnf(u238_subst,axiom,\n    (((c_In @ n @ int)) != $true) | (((c_SNo @ n)) = $true)).\n" "parent_1_substitution=[0 -> X0]" "parent_1_substituted_clause=cnf(u237_subst,axiom,\n    (((c_In @ n @ int)) = $true)).\n" "parent_1_substituted_clause_db_indices=cnf(u237_subst,axiom,\n    (((c_In @ n @ int)) = $true)).\n"))
  (step_proposition "u298" "vampire_eq_prop (SNo n) (vampire_true)")
  (step_proposition "u299" "vampire_eq_prop (vampire_true) (vampire_false)")
  (step_extra "u299" "rewrite" ("lhs=c_SNo @ n" "target=c_SNo @ n" "rule_lhs=SNo n" "redex=SNo n" "rule_rhs=vampire_false" "replacement=vampire_false" "rule_lhs=SNo n" "rule_rhs=vampire_false" "redex=SNo n" "replacement=vampire_false" "parent_0_substitution=[]" "parent_0_substituted_clause=cnf(u298_subst,axiom,\n    (((c_SNo @ n)) = $true)).\n" "parent_0_substituted_clause_db_indices=cnf(u298_subst,axiom,\n    (((c_SNo @ n)) = $true)).\n" "parent_1_substitution=[]" "parent_1_substituted_clause=cnf(u245_subst,axiom,\n    (((c_SNo @ n)) = $false)).\n" "parent_1_substituted_clause_db_indices=cnf(u245_subst,axiom,\n    (((c_SNo @ n)) = $false)).\n"))
  (step_proposition "u300" "vampire_false")
  (symbol_declaration "Variable In:set->set->prop.")
  (symbol_declaration "Variable SNo:set->prop.")
  (symbol_declaration "Variable int:set.")
  (symbol_declaration "Variable n:set.")
  (symbol_declaration "Variable f__false:prop.")
  (symbol_declaration "Variable f__true:prop.")
  (formula_term_input "u68" (source axiom "int_5FSNo") (formula (ALL (SET) (IMP (AP (AP (TMH "In") (TMH "X0")) (TMH "int")) (AP (TMH "SNo") (TMH "X0"))))))
  (formula_input "u77" (source axiom "c_Hn") (pos (AP (AP (TMH "In") (TMH "n")) (TMH "int"))))
  (formula_input "u78" (source conjecture "conj_c__2Fproject_2Ftmp_2Fmegalodon3_5Fsource_5Flinked_5Fcorpus_5F250_2Fhammer_5F11978_5F17") (pos (AP (TMH "SNo") (TMH "n"))))
  (formula_term_input "u79" (source negated_conjecture "conj_c__2Fproject_2Ftmp_2Fmegalodon3_5Fsource_5Flinked_5Fcorpus_5F250_2Fhammer_5F11978_5F17") (formula (IMP (AP (TMH "SNo") (TMH "n")) (TMH "vampire_false"))))
  (rectify_formula "u212" (parent "u68") (renamings (renaming (source (formula (ALL (SET) (IMP (AP (AP (TMH "In") (TMH "X0")) (TMH "int")) (AP (TMH "SNo") (TMH "X0")))))) (subst) (target (formula (ALL (SET) (IMP (AP (AP (TMH "In") (TMH "X0")) (TMH "int")) (AP (TMH "SNo") (TMH "X0")))))))) (result (formula (ALL (SET) (IMP (AP (AP (TMH "In") (TMH "X0")) (TMH "int")) (AP (TMH "SNo") (TMH "X0")))))))
  (fool_formula "u213" (parent "u212") (result (formula (ALL (SET) (IMP (AP (AP (TMH "=") (AP (AP (TMH "In") (TMH "X0")) (TMH "int"))) (TMH "f__true")) (AP (AP (TMH "=") (AP (TMH "SNo") (TMH "X0"))) (TMH "f__true")))))))
  (rectify_formula "u230" (parent "u77") (result (formula (AP (AP (TMH "In") (TMH "n")) (TMH "int")))))
  (fool_bool "u231" (parent "u230") (result (pos (AP (AP (TMH "=") (AP (AP (TMH "In") (TMH "n")) (TMH "int"))) (TMH "f__true")))))
  (rectify_formula "u232" (parent "u79") (result (formula (IMP (AP (TMH "SNo") (TMH "n")) (TMH "vampire_false")))))
  (fool_bool "u233" (parent "u232") (result (neg (AP (AP (TMH "=") (AP (TMH "SNo") (TMH "n"))) (TMH "f__true")))))
  (formula_copy "u234" (parent "u233") (result (neg (AP (AP (TMH "=") (AP (TMH "SNo") (TMH "n"))) (TMH "f__true")))))
  (ennf_formula "u235" (parent "u213") (result (formula (ALL (SET) (AP (AP (TMH "vampire_or") (IMP (AP (AP (TMH "=") (AP (AP (TMH "In") (TMH "X0")) (TMH "int"))) (TMH "f__true")) (TMH "vampire_false"))) (AP (AP (TMH "=") (AP (TMH "SNo") (TMH "X0"))) (TMH "f__true")))))))
  (cnf_literal "u236" (parent "u234") (result (clause (neg (AP (AP (TMH "=") (AP (TMH "SNo") (TMH "n"))) (TMH "f__true"))))))
  (cnf_literal "u237" (parent "u231") (result (clause (pos (AP (AP (TMH "=") (AP (AP (TMH "In") (TMH "n")) (TMH "int"))) (TMH "f__true"))))))
  (cnf_formula_clause "u238" (parent "u235") (index 0) (result (clause (neg (AP (AP (TMH "=") (AP (AP (TMH "In") (TMH "X0")) (TMH "int"))) (TMH "f__true"))) (pos (AP (AP (TMH "=") (AP (TMH "SNo") (TMH "X0"))) (TMH "f__true"))))))
  (fool_exhaustiveness "u240" (result (clause (pos (AP (AP (TMH "=") (TMH "f__true")) (TMH "X0"))) (pos (AP (AP (TMH "=") (TMH "f__false")) (TMH "X0"))))))
  (substitute "u243_subst0" (parent "u236") (subst) (result (clause (neg (AP (AP (TMH "=") (AP (TMH "SNo") (TMH "n"))) (TMH "f__true"))))))
  (substitute "u243_subst1" (parent "u240") (subst ("X0" (AP (TMH "SNo") (TMH "n")))) (result (clause (pos (AP (AP (TMH "=") (TMH "f__true")) (AP (TMH "SNo") (TMH "n")))) (pos (AP (AP (TMH "=") (TMH "f__false")) (AP (TMH "SNo") (TMH "n")))))))
  (paramodulate "u243_paramodulate" (equality "u243_subst1" 0) (target "u243_subst0" 0) (position 0 1) (from (AP (TMH "SNo") (TMH "n"))) (to (TMH "f__true")) (result (clause (pos (AP (AP (TMH "=") (TMH "f__false")) (AP (TMH "SNo") (TMH "n")))) (neg (AP (AP (TMH "=") (TMH "f__true")) (TMH "f__true"))))))
  (equality_symmetry "u243_symmetry0" (parent "u243_paramodulate") (literal 0) (result (clause (pos (AP (AP (TMH "=") (AP (TMH "SNo") (TMH "n"))) (TMH "f__false"))) (neg (AP (AP (TMH "=") (TMH "f__true")) (TMH "f__true"))))))
  (substitute "u243" (parent "u243_symmetry0") (subst) (result (clause (neg (AP (AP (TMH "=") (TMH "f__true")) (TMH "f__true"))) (pos (AP (AP (TMH "=") (AP (TMH "SNo") (TMH "n"))) (TMH "f__false"))))))
  (equality_resolution "u245" (parent "u243") (literal 0) (result (clause (pos (AP (AP (TMH "=") (AP (TMH "SNo") (TMH "n"))) (TMH "f__false"))))))
  (substitute "u291_subst0" (parent "u238") (subst ("X0" (TMH "n"))) (result (clause (neg (AP (AP (TMH "=") (AP (AP (TMH "In") (TMH "n")) (TMH "int"))) (TMH "f__true"))) (pos (AP (AP (TMH "=") (AP (TMH "SNo") (TMH "n"))) (TMH "f__true"))))))
  (substitute "u291_subst1" (parent "u237") (subst) (result (clause (pos (AP (AP (TMH "=") (AP (AP (TMH "In") (TMH "n")) (TMH "int"))) (TMH "f__true"))))))
  (paramodulate "u291" (equality "u291_subst1" 0) (target "u291_subst0" 0) (position 0 1) (from (AP (AP (TMH "In") (TMH "n")) (TMH "int"))) (to (TMH "f__true")) (result (clause (neg (AP (AP (TMH "=") (TMH "f__true")) (TMH "f__true"))) (pos (AP (AP (TMH "=") (AP (TMH "SNo") (TMH "n"))) (TMH "f__true"))))))
  (equality_resolution "u298" (parent "u291") (literal 0) (result (clause (pos (AP (AP (TMH "=") (AP (TMH "SNo") (TMH "n"))) (TMH "f__true"))))))
  (paramodulate "u299" (equality "u245" 0) (target "u298" 0) (position 0 1) (from (AP (TMH "SNo") (TMH "n"))) (to (TMH "f__false")) (result (clause (pos (AP (AP (TMH "=") (TMH "f__true")) (TMH "f__false"))))))
  (truth_conflict "u300" (parent "u299") (literal 0) (result (clause)))
)
