(certificate vampire-megalodon 1
  (problem "vampire-native-certificate")
  (step_proposition "u68" "forall X0:set, In X0 int -> SNo X0")
  (step_variable_sorts "u68" ("X0:set"))
  (step_proposition "u72" "In b int")
  (step_proposition "u73" "SNo b")
  (step_proposition "u74" "(SNo b) -> vampire_false")
  (step_proposition "u207" "forall X0:set, In X0 int -> SNo X0")
  (step_variable_sorts "u207" ("X0:set"))
  (step_extra "u207" "rectify" ("rule=rectify" "source=forall X0:set, In X0 int -> SNo X0" "target=forall X0:set, In X0 int -> SNo X0" "renaming_count=1" "renaming_0_source=forall X0:set, In X0 int -> SNo X0" "renaming_0_source_substituted=forall X0:set, In X0 int -> SNo X0" "renaming_0_target=forall X0:set, In X0 int -> SNo X0"))
  (step_proposition "u208" "forall X0:set, vampire_eq_prop (In X0 int) (vampire_true) -> vampire_eq_prop (SNo X0) (vampire_true)")
  (step_variable_sorts "u208" ("X0:set"))
  (step_extra "u208" "fool" ("rule=fool elimination" "source=forall X0:set, In X0 int -> SNo X0" "target=forall X0:set, vampire_eq_prop (In X0 int) (vampire_true) -> vampire_eq_prop (SNo X0) (vampire_true)" "pair_0_source=forall X0:set, In X0 int -> SNo X0" "pair_0_target=forall X0:set, vampire_eq_prop (In X0 int) (vampire_true) -> vampire_eq_prop (SNo X0) (vampire_true)" "pair_1_source=In X0 int -> SNo X0" "pair_1_target=vampire_eq_prop (In X0 int) (vampire_true) -> vampire_eq_prop (SNo X0) (vampire_true)" "pair_2_source=In X0 int" "pair_2_target=vampire_eq_prop (In X0 int) (vampire_true)" "pair_3_source=SNo X0" "pair_3_target=vampire_eq_prop (SNo X0) (vampire_true)"))
  (step_proposition "u215" "In b int")
  (step_extra "u215" "rectify" ("rule=rectify" "source=In b int" "target=In b int" "renaming_count=0"))
  (step_proposition "u216" "vampire_eq_prop (In b int) (vampire_true)")
  (step_extra "u216" "fool" ("rule=fool elimination" "source=In b int" "target=vampire_eq_prop (In b int) (vampire_true)" "pair_0_source=In b int" "pair_0_target=vampire_eq_prop (In b int) (vampire_true)"))
  (step_extra "u216" "raw" ("number=1"))
  (step_proposition "u217" "(SNo b) -> vampire_false")
  (step_extra "u217" "rectify" ("rule=rectify" "source=(SNo b) -> vampire_false" "target=(SNo b) -> vampire_false" "renaming_count=0"))
  (step_proposition "u218" "(vampire_eq_prop (SNo b) (vampire_true)) -> vampire_false")
  (step_extra "u218" "fool" ("rule=fool elimination" "source=(SNo b) -> vampire_false" "target=(vampire_eq_prop (SNo b) (vampire_true)) -> vampire_false" "pair_0_source=(SNo b) -> vampire_false" "pair_0_target=(vampire_eq_prop (SNo b) (vampire_true)) -> vampire_false" "pair_1_source=SNo b" "pair_1_target=vampire_eq_prop (SNo b) (vampire_true)"))
  (step_proposition "u219" "(vampire_eq_prop (SNo b) (vampire_true)) -> vampire_false")
  (step_extra "u219" "normal_form" ("rule=flattening" "source=(vampire_eq_prop (SNo b) (vampire_true)) -> vampire_false" "target=(vampire_eq_prop (SNo b) (vampire_true)) -> vampire_false"))
  (step_extra "u219" "raw" ("number=1"))
  (step_proposition "u220" "forall X0:set, vampire_or ((vampire_eq_prop (In X0 int) (vampire_true)) -> vampire_false) (vampire_eq_prop (SNo X0) (vampire_true))")
  (step_variable_sorts "u220" ("X0:set"))
  (step_extra "u220" "normal_form" ("rule=ennf transformation" "source=forall X0:set, vampire_eq_prop (In X0 int) (vampire_true) -> vampire_eq_prop (SNo X0) (vampire_true)" "target=forall X0:set, vampire_or ((vampire_eq_prop (In X0 int) (vampire_true)) -> vampire_false) (vampire_eq_prop (SNo X0) (vampire_true))" "pair_0_source=forall X0:set, vampire_eq_prop (In X0 int) (vampire_true) -> vampire_eq_prop (SNo X0) (vampire_true)" "pair_0_target=forall X0:set, vampire_or ((vampire_eq_prop (In X0 int) (vampire_true)) -> vampire_false) (vampire_eq_prop (SNo X0) (vampire_true))" "pair_0_path=root" "pair_1_source=vampire_eq_prop (In X0 int) (vampire_true) -> vampire_eq_prop (SNo X0) (vampire_true)" "pair_1_target=vampire_or ((vampire_eq_prop (In X0 int) (vampire_true)) -> vampire_false) (vampire_eq_prop (SNo X0) (vampire_true))" "pair_1_path=root.body" "pair_2_source=vampire_eq_prop (In X0 int) (vampire_true) -> false" "pair_2_target=(vampire_eq_prop (In X0 int) (vampire_true)) -> vampire_false" "pair_2_path=root.body.ennf_imp_left"))
  (step_extra "u220" "raw" ("number=1"))
  (step_proposition "u221" "(vampire_eq_prop (SNo b) (vampire_true)) -> vampire_false")
  (step_extra "u221" "cnf" ("rule=cnf transformation" "parent_unit=219" "parent_kind=formula" "source=(vampire_eq_prop (SNo b) (vampire_true)) -> vampire_false" "source_proposition=(vampire_eq_prop (SNo b) (vampire_true)) -> vampire_false" "target=(vampire_eq_prop (SNo b) (vampire_true)) -> vampire_false" "target_proposition=(vampire_eq_prop (SNo b) (vampire_true)) -> vampire_false" "target_clause=[{\"polarity\":false,\"atom\":{\"eq\":[{\"apply\":[{\"const\":\"SNo\"},{\"const\":\"b\"}]},{\"const\":\"f__true\"}],\"sort\":\"prop\"}}]" "target_literal_count=1" "target_literal_0=(vampire_eq_prop (SNo b) (vampire_true)) -> vampire_false" "parent_clause_count=1" "clause_parent_unit=219" "clause_index=0" "clause_count=1" "target_variable_sort_count=0"))
  (step_extra "u221" "raw" ("parent=219,index=0,count=1"))
  (step_proposition "u222" "forall X0:set, vampire_or ((vampire_eq_prop (In X0 int) (vampire_true)) -> vampire_false) (vampire_eq_prop (SNo X0) (vampire_true))")
  (step_variable_sorts "u222" ("X0:set"))
  (step_extra "u222" "cnf" ("rule=cnf transformation" "parent_unit=220" "parent_kind=formula" "source=forall X0:set, vampire_or ((vampire_eq_prop (In X0 int) (vampire_true)) -> vampire_false) (vampire_eq_prop (SNo X0) (vampire_true))" "source_proposition=forall X0:set, vampire_or ((vampire_eq_prop (In X0 int) (vampire_true)) -> vampire_false) (vampire_eq_prop (SNo X0) (vampire_true))" "target=forall X0:set, vampire_or ((vampire_eq_prop (In X0 int) (vampire_true)) -> vampire_false) (vampire_eq_prop (SNo X0) (vampire_true))" "target_proposition=forall X0:set, vampire_or ((vampire_eq_prop (In X0 int) (vampire_true)) -> vampire_false) (vampire_eq_prop (SNo X0) (vampire_true))" "target_clause=[{\"polarity\":false,\"atom\":{\"eq\":[{\"apply\":[{\"apply\":[{\"const\":\"In\"},{\"var\":\"X0\"}]},{\"const\":\"int\"}]},{\"const\":\"f__true\"}],\"sort\":\"prop\"}},{\"polarity\":true,\"atom\":{\"eq\":[{\"apply\":[{\"const\":\"SNo\"},{\"var\":\"X0\"}]},{\"const\":\"f__true\"}],\"sort\":\"prop\"}}]" "target_literal_count=2" "target_literal_0=(vampire_eq_prop (In X0 int) (vampire_true)) -> vampire_false" "target_literal_1=vampire_eq_prop (SNo X0) (vampire_true)" "parent_clause_count=1" "clause_parent_unit=220" "clause_index=0" "clause_count=1" "target_variable_sort_count=1" "target_variable_sort_0=X0:set"))
  (step_extra "u222" "raw" ("parent=220,index=0,count=1"))
  (step_proposition "u224" "vampire_eq_prop (In b int) (vampire_true)")
  (step_extra "u224" "cnf" ("rule=cnf transformation" "parent_unit=216" "parent_kind=formula" "source=vampire_eq_prop (In b int) (vampire_true)" "source_proposition=vampire_eq_prop (In b int) (vampire_true)" "target=vampire_eq_prop (In b int) (vampire_true)" "target_proposition=vampire_eq_prop (In b int) (vampire_true)" "target_clause=[{\"polarity\":true,\"atom\":{\"eq\":[{\"apply\":[{\"apply\":[{\"const\":\"In\"},{\"const\":\"b\"}]},{\"const\":\"int\"}]},{\"const\":\"f__true\"}],\"sort\":\"prop\"}}]" "target_literal_count=1" "target_literal_0=vampire_eq_prop (In b int) (vampire_true)" "parent_clause_count=1" "clause_parent_unit=216" "clause_index=0" "clause_count=1" "target_variable_sort_count=0"))
  (step_extra "u224" "raw" ("parent=216,index=0,count=1"))
  (step_proposition "u270" "forall X0:prop, vampire_or (vampire_eq_prop (vampire_true) (X0)) (vampire_eq_prop (vampire_false) (X0))")
  (step_variable_sorts "u270" ("X0:prop"))
  (step_proposition "u273" "vampire_or ((vampire_eq_prop (vampire_true) (vampire_true)) -> vampire_false) (vampire_eq_prop (SNo b) (vampire_false))")
  (step_extra "u273" "two_literal_rewrite" ("selected=(((c_SNo @ b)) != $true)" "other=($true = X0)" "selected_parent_index=0" "selected_literal_index=0" "selected_parent_unit=221" "selected_substituted=(((c_SNo @ b)) != $true)" "selected_substituted_db_indices=(((c_SNo @ b)) != $true)" "selected_substituted_proposition=(vampire_eq_prop (SNo b) (vampire_true)) -> vampire_false" "other_parent_index=1" "other_literal_index=0" "other_parent_unit=270" "other_substituted=(((c_SNo @ b)) = $true)" "other_substituted_db_indices=(((c_SNo @ b)) = $true)" "other_substituted_proposition=vampire_eq_prop (SNo b) (vampire_true)" "lhs=X0" "target=c_SNo @ b" "lhs_term=X0" "target_term=SNo b" "target_sort=prop" "parent_0_substitution=[0 -> X0]" "parent_0_substituted_clause=cnf(u221_subst,axiom,\n    (((c_SNo @ b)) != $true)).\n" "parent_0_substituted_clause_db_indices=cnf(u221_subst,axiom,\n    (((c_SNo @ b)) != $true)).\n" "parent_1_substitution=[0 -> c_SNo @ b]" "parent_1_substituted_clause=cnf(u270_subst,axiom,\n    (((c_SNo @ b)) = $true) | (((c_SNo @ b)) = $false)).\n" "parent_1_substituted_clause_db_indices=cnf(u270_subst,axiom,\n    (((c_SNo @ b)) = $true) | (((c_SNo @ b)) = $false)).\n"))
  (step_proposition "u275" "vampire_eq_prop (SNo b) (vampire_false)")
  (step_proposition "u321" "vampire_or ((vampire_eq_prop (vampire_true) (vampire_true)) -> vampire_false) (vampire_eq_prop (SNo b) (vampire_true))")
  (step_extra "u321" "two_literal_rewrite" ("selected=(((c_In @ X0 @ int)) != $true)" "other=(((c_In @ b @ int)) = $true)" "selected_parent_index=0" "selected_literal_index=0" "selected_parent_unit=222" "selected_substituted=(((c_In @ b @ int)) != $true)" "selected_substituted_db_indices=(((c_In @ b @ int)) != $true)" "selected_substituted_proposition=(vampire_eq_prop (In b int) (vampire_true)) -> vampire_false" "other_parent_index=1" "other_literal_index=0" "other_parent_unit=224" "other_substituted=(((c_In @ b @ int)) = $true)" "other_substituted_db_indices=(((c_In @ b @ int)) = $true)" "other_substituted_proposition=vampire_eq_prop (In b int) (vampire_true)" "lhs=c_In @ b @ int" "target=c_In @ X0 @ int" "lhs_term=In b int" "target_term=In X0 int" "lhs_sort=prop" "target_sort=prop" "parent_0_substitution=[0 -> b]" "parent_0_substituted_clause=cnf(u222_subst,axiom,\n    (((c_In @ b @ int)) != $true) | (((c_SNo @ b)) = $true)).\n" "parent_0_substituted_clause_db_indices=cnf(u222_subst,axiom,\n    (((c_In @ b @ int)) != $true) | (((c_SNo @ b)) = $true)).\n" "parent_1_substitution=[0 -> X0]" "parent_1_substituted_clause=cnf(u224_subst,axiom,\n    (((c_In @ b @ int)) = $true)).\n" "parent_1_substituted_clause_db_indices=cnf(u224_subst,axiom,\n    (((c_In @ b @ int)) = $true)).\n"))
  (step_proposition "u328" "vampire_eq_prop (SNo b) (vampire_true)")
  (step_proposition "u331" "vampire_eq_prop (vampire_true) (vampire_false)")
  (step_extra "u331" "rewrite" ("lhs=c_SNo @ b" "target=c_SNo @ b" "rule_lhs=SNo b" "redex=SNo b" "rule_rhs=vampire_false" "replacement=vampire_false" "rule_lhs=SNo b" "rule_rhs=vampire_false" "redex=SNo b" "replacement=vampire_false" "parent_0_substitution=[]" "parent_0_substituted_clause=cnf(u328_subst,axiom,\n    (((c_SNo @ b)) = $true)).\n" "parent_0_substituted_clause_db_indices=cnf(u328_subst,axiom,\n    (((c_SNo @ b)) = $true)).\n" "parent_1_substitution=[]" "parent_1_substituted_clause=cnf(u275_subst,axiom,\n    (((c_SNo @ b)) = $false)).\n" "parent_1_substituted_clause_db_indices=cnf(u275_subst,axiom,\n    (((c_SNo @ b)) = $false)).\n"))
  (step_proposition "u332" "vampire_false")
  (symbol_declaration "Variable In:set->set->prop.")
  (symbol_declaration "Variable SNo:set->prop.")
  (symbol_declaration "Variable int:set.")
  (symbol_declaration "Variable b:set.")
  (symbol_declaration "Variable f__false:prop.")
  (symbol_declaration "Variable f__true:prop.")
  (formula_term_input "u68" (source axiom "int_5FSNo") (formula (ALL (SET) (IMP (AP (AP (TMH "In") (TMH "X0")) (TMH "int")) (AP (TMH "SNo") (TMH "X0"))))))
  (formula_input "u72" (source axiom "c_Hb") (pos (AP (AP (TMH "In") (TMH "b")) (TMH "int"))))
  (formula_input "u73" (source conjecture "conj_c__2Fproject_2Ftmp_2Fsource_5Flinked_5Fstrict_5F100_5Fcorpus_5Ffresh_5F041947_2Fhammer_5F11080_5F17") (pos (AP (TMH "SNo") (TMH "b"))))
  (formula_term_input "u74" (source negated_conjecture "conj_c__2Fproject_2Ftmp_2Fsource_5Flinked_5Fstrict_5F100_5Fcorpus_5Ffresh_5F041947_2Fhammer_5F11080_5F17") (formula (IMP (AP (TMH "SNo") (TMH "b")) (TMH "vampire_false"))))
  (rectify_formula "u207" (parent "u68") (renamings (renaming (source (formula (ALL (SET) (IMP (AP (AP (TMH "In") (TMH "X0")) (TMH "int")) (AP (TMH "SNo") (TMH "X0")))))) (subst) (target (formula (ALL (SET) (IMP (AP (AP (TMH "In") (TMH "X0")) (TMH "int")) (AP (TMH "SNo") (TMH "X0")))))))) (result (formula (ALL (SET) (IMP (AP (AP (TMH "In") (TMH "X0")) (TMH "int")) (AP (TMH "SNo") (TMH "X0")))))))
  (fool_formula "u208" (parent "u207") (result (formula (ALL (SET) (IMP (AP (AP (TMH "=") (AP (AP (TMH "In") (TMH "X0")) (TMH "int"))) (TMH "f__true")) (AP (AP (TMH "=") (AP (TMH "SNo") (TMH "X0"))) (TMH "f__true")))))))
  (rectify_formula "u215" (parent "u72") (result (formula (AP (AP (TMH "In") (TMH "b")) (TMH "int")))))
  (fool_bool "u216" (parent "u215") (result (pos (AP (AP (TMH "=") (AP (AP (TMH "In") (TMH "b")) (TMH "int"))) (TMH "f__true")))))
  (rectify_formula "u217" (parent "u74") (result (formula (IMP (AP (TMH "SNo") (TMH "b")) (TMH "vampire_false")))))
  (fool_bool "u218" (parent "u217") (result (neg (AP (AP (TMH "=") (AP (TMH "SNo") (TMH "b"))) (TMH "f__true")))))
  (formula_copy "u219" (parent "u218") (result (neg (AP (AP (TMH "=") (AP (TMH "SNo") (TMH "b"))) (TMH "f__true")))))
  (ennf_formula "u220" (parent "u208") (result (formula (ALL (SET) (AP (AP (TMH "vampire_or") (IMP (AP (AP (TMH "=") (AP (AP (TMH "In") (TMH "X0")) (TMH "int"))) (TMH "f__true")) (TMH "vampire_false"))) (AP (AP (TMH "=") (AP (TMH "SNo") (TMH "X0"))) (TMH "f__true")))))))
  (cnf_literal "u221" (parent "u219") (result (clause (neg (AP (AP (TMH "=") (AP (TMH "SNo") (TMH "b"))) (TMH "f__true"))))))
  (cnf_formula_clause "u222" (parent "u220") (index 0) (result (clause (neg (AP (AP (TMH "=") (AP (AP (TMH "In") (TMH "X0")) (TMH "int"))) (TMH "f__true"))) (pos (AP (AP (TMH "=") (AP (TMH "SNo") (TMH "X0"))) (TMH "f__true"))))))
  (cnf_literal "u224" (parent "u216") (result (clause (pos (AP (AP (TMH "=") (AP (AP (TMH "In") (TMH "b")) (TMH "int"))) (TMH "f__true"))))))
  (fool_exhaustiveness "u270" (result (clause (pos (AP (AP (TMH "=") (TMH "f__true")) (TMH "X0"))) (pos (AP (AP (TMH "=") (TMH "f__false")) (TMH "X0"))))))
  (substitute "u273_subst0" (parent "u221") (subst) (result (clause (neg (AP (AP (TMH "=") (AP (TMH "SNo") (TMH "b"))) (TMH "f__true"))))))
  (substitute "u273_subst1" (parent "u270") (subst ("X0" (AP (TMH "SNo") (TMH "b")))) (result (clause (pos (AP (AP (TMH "=") (TMH "f__true")) (AP (TMH "SNo") (TMH "b")))) (pos (AP (AP (TMH "=") (TMH "f__false")) (AP (TMH "SNo") (TMH "b")))))))
  (paramodulate "u273_paramodulate" (equality "u273_subst1" 0) (target "u273_subst0" 0) (position 0 1) (from (AP (TMH "SNo") (TMH "b"))) (to (TMH "f__true")) (result (clause (pos (AP (AP (TMH "=") (TMH "f__false")) (AP (TMH "SNo") (TMH "b")))) (neg (AP (AP (TMH "=") (TMH "f__true")) (TMH "f__true"))))))
  (equality_symmetry "u273_symmetry0" (parent "u273_paramodulate") (literal 0) (result (clause (pos (AP (AP (TMH "=") (AP (TMH "SNo") (TMH "b"))) (TMH "f__false"))) (neg (AP (AP (TMH "=") (TMH "f__true")) (TMH "f__true"))))))
  (substitute "u273" (parent "u273_symmetry0") (subst) (result (clause (neg (AP (AP (TMH "=") (TMH "f__true")) (TMH "f__true"))) (pos (AP (AP (TMH "=") (AP (TMH "SNo") (TMH "b"))) (TMH "f__false"))))))
  (equality_resolution "u275" (parent "u273") (literal 0) (result (clause (pos (AP (AP (TMH "=") (AP (TMH "SNo") (TMH "b"))) (TMH "f__false"))))))
  (substitute "u321_subst0" (parent "u222") (subst ("X0" (TMH "b"))) (result (clause (neg (AP (AP (TMH "=") (AP (AP (TMH "In") (TMH "b")) (TMH "int"))) (TMH "f__true"))) (pos (AP (AP (TMH "=") (AP (TMH "SNo") (TMH "b"))) (TMH "f__true"))))))
  (substitute "u321_subst1" (parent "u224") (subst) (result (clause (pos (AP (AP (TMH "=") (AP (AP (TMH "In") (TMH "b")) (TMH "int"))) (TMH "f__true"))))))
  (paramodulate "u321" (equality "u321_subst1" 0) (target "u321_subst0" 0) (position 0 1) (from (AP (AP (TMH "In") (TMH "b")) (TMH "int"))) (to (TMH "f__true")) (result (clause (neg (AP (AP (TMH "=") (TMH "f__true")) (TMH "f__true"))) (pos (AP (AP (TMH "=") (AP (TMH "SNo") (TMH "b"))) (TMH "f__true"))))))
  (equality_resolution "u328" (parent "u321") (literal 0) (result (clause (pos (AP (AP (TMH "=") (AP (TMH "SNo") (TMH "b"))) (TMH "f__true"))))))
  (paramodulate "u331" (equality "u275" 0) (target "u328" 0) (position 0 1) (from (AP (TMH "SNo") (TMH "b"))) (to (TMH "f__false")) (result (clause (pos (AP (AP (TMH "=") (TMH "f__true")) (TMH "f__false"))))))
  (truth_conflict "u332" (parent "u331") (literal 0) (result (clause)))
)
