(certificate vampire-megalodon 1
  (problem "vampire-native-certificate")
  (step_proposition "u65" "Empty = SNoLev Empty")
  (step_extra "u65" "raw" ("number=1"))
  (step_proposition "u77" "Empty = SNoLev Empty")
  (step_proposition "u78" "(Empty = SNoLev Empty) -> vampire_false")
  (step_proposition "u226" "(Empty = SNoLev Empty) -> vampire_false")
  (step_extra "u226" "normal_form" ("rule=flattening" "source=(Empty = SNoLev Empty) -> vampire_false" "target=(Empty = SNoLev Empty) -> vampire_false"))
  (step_extra "u226" "raw" ("number=1"))
  (step_proposition "u291" "Empty = SNoLev Empty")
  (step_extra "u291" "cnf" ("rule=cnf transformation" "parent_unit=65" "parent_kind=formula" "source=Empty = SNoLev Empty" "source_proposition=Empty = SNoLev Empty" "target=Empty = SNoLev Empty" "target_proposition=Empty = SNoLev Empty" "target_clause=[{\"polarity\":true,\"atom\":{\"eq\":[{\"const\":\"Empty\"},{\"apply\":[{\"const\":\"SNoLev\"},{\"const\":\"Empty\"}]}]}}]" "target_literal_count=1" "target_literal_0=Empty = SNoLev Empty" "parent_clause_count=1" "clause_parent_unit=65" "clause_index=0" "clause_count=1" "target_variable_sort_count=0"))
  (step_extra "u291" "raw" ("parent=65,index=0,count=1"))
  (step_proposition "u303" "(Empty = SNoLev Empty) -> vampire_false")
  (step_extra "u303" "cnf" ("rule=cnf transformation" "parent_unit=226" "parent_kind=formula" "source=(Empty = SNoLev Empty) -> vampire_false" "source_proposition=(Empty = SNoLev Empty) -> vampire_false" "target=(Empty = SNoLev Empty) -> vampire_false" "target_proposition=(Empty = SNoLev Empty) -> vampire_false" "target_clause=[{\"polarity\":false,\"atom\":{\"eq\":[{\"const\":\"Empty\"},{\"apply\":[{\"const\":\"SNoLev\"},{\"const\":\"Empty\"}]}]}}]" "target_literal_count=1" "target_literal_0=(Empty = SNoLev Empty) -> vampire_false" "parent_clause_count=1" "clause_parent_unit=226" "clause_index=0" "clause_count=1" "target_variable_sort_count=0"))
  (step_extra "u303" "raw" ("parent=226,index=0,count=1"))
  (step_proposition "u306" "SNoLev Empty = sF0")
  (step_extra "u306" "function_definition" ("introduced_symbol=sF0" "sort=set" "equality_sort=set" "lhs=SNoLev Empty" "rhs=sF0" "proposition=SNoLev Empty = sF0"))
  (step_proposition "u307" "(Empty = sF0) -> vampire_false")
  (step_extra "u307" "definition_rewrite" ("rule=definition folding" "target=(Empty = sF0) -> vampire_false" "parent_0=(Empty = SNoLev Empty) -> vampire_false" "source=(Empty = SNoLev Empty) -> vampire_false" "parent_1=SNoLev Empty = sF0" "definition=SNoLev Empty = sF0" "fold_step_count=1" "fold_step_0_lhs=SNoLev Empty" "fold_step_0_rhs=sF0" "fold_step_0_literal=0" "fold_step_0_position=1"))
  (step_extra "u307" "raw" ("steps=1,step0=(c_SNoLev @ c_Empty -> sF0)@0:1"))
  (step_proposition "u308" "Empty = sF0")
  (step_extra "u308" "rewrite" ("lhs=c_SNoLev @ c_Empty" "target=c_SNoLev @ c_Empty" "rule_lhs=SNoLev Empty" "redex=SNoLev Empty" "rule_rhs=Empty" "replacement=Empty" "rule_lhs=SNoLev Empty" "rule_rhs=Empty" "redex=SNoLev Empty" "replacement=Empty" "parent_0_substitution=[]" "parent_0_substituted_clause=cnf(u306_subst,axiom,\n    (((c_SNoLev @ c_Empty)) = sF0)).\n" "parent_0_substituted_clause_db_indices=cnf(u306_subst,axiom,\n    (((c_SNoLev @ c_Empty)) = sF0)).\n" "parent_1_substitution=[]" "parent_1_substituted_clause=cnf(u291_subst,axiom,\n    (c_Empty = ((c_SNoLev @ c_Empty)))).\n" "parent_1_substituted_clause_db_indices=cnf(u291_subst,axiom,\n    (c_Empty = ((c_SNoLev @ c_Empty)))).\n"))
  (step_proposition "u309" "vampire_false")
  (step_extra "u309" "literal" ("selected=(c_Empty = sF0)" "selected_parent_index=0" "selected_literal_index=0" "selected_parent_unit=308" "selected_substitution_source=sat_subsumption" "selected_substitution=[]" "selected_substituted=(c_Empty = sF0)" "selected_substituted_db_indices=(c_Empty = sF0)" "selected_substituted_proposition=Empty = sF0"))
  (symbol_declaration "Variable Empty:set.")
  (symbol_declaration "Variable SNoLev:set->set.")
  (symbol_declaration "Variable sF0:set.")
  (formula_input "u65" (source axiom "c_SNoLev_5F0") (pos (AP (AP (TMH "=") (TMH "Empty")) (AP (TMH "SNoLev") (TMH "Empty")))))
  (formula_input "u77" (source conjecture "conj_c__2Fproject_2Ftmp_2Fsource_5Flinked_5Fstrict_5F100_5Fcorpus_5Ffresh_5F041947_2Fhammer_5F11555_5F42") (pos (AP (AP (TMH "=") (TMH "Empty")) (AP (TMH "SNoLev") (TMH "Empty")))))
  (formula_term_input "u78" (source negated_conjecture "conj_c__2Fproject_2Ftmp_2Fsource_5Flinked_5Fstrict_5F100_5Fcorpus_5Ffresh_5F041947_2Fhammer_5F11555_5F42") (formula (IMP (AP (AP (TMH "=") (TMH "Empty")) (AP (TMH "SNoLev") (TMH "Empty"))) (TMH "vampire_false"))))
  (formula_copy "u226" (parent "u78") (result (neg (AP (AP (TMH "=") (TMH "Empty")) (AP (TMH "SNoLev") (TMH "Empty"))))))
  (cnf_literal "u291" (parent "u65") (result (clause (pos (AP (AP (TMH "=") (TMH "Empty")) (AP (TMH "SNoLev") (TMH "Empty")))))))
  (cnf_literal "u303" (parent "u226") (result (clause (neg (AP (AP (TMH "=") (TMH "Empty")) (AP (TMH "SNoLev") (TMH "Empty")))))))
  (definition_input "u306" (result (clause (pos (AP (AP (TMH "=") (AP (TMH "SNoLev") (TMH "Empty"))) (TMH "sF0"))))))
  (paramodulate "u307" (equality "u306" 0) (target "u303" 0) (position 1) (from (AP (TMH "SNoLev") (TMH "Empty"))) (to (TMH "sF0")) (result (clause (neg (AP (AP (TMH "=") (TMH "Empty")) (TMH "sF0"))))))
  (equality_symmetry "u308_symmetry" (parent "u291") (literal 0) (result (clause (pos (AP (AP (TMH "=") (AP (TMH "SNoLev") (TMH "Empty"))) (TMH "Empty"))))))
  (paramodulate "u308" (equality "u308_symmetry" 0) (target "u306" 0) (position 0 1) (from (AP (TMH "SNoLev") (TMH "Empty"))) (to (TMH "Empty")) (result (clause (pos (AP (AP (TMH "=") (TMH "Empty")) (TMH "sF0"))))))
  (resolve "u309" (parents "u308" "u307") (pivot 0 0) (result (clause)))
)
