(certificate vampire-megalodon 1
  (problem "vampire-native-certificate")
  (step_proposition "u78" "Empty = Empty")
  (step_proposition "u79" "(Empty = Empty) -> vampire_false")
  (step_proposition "u229" "(Empty = Empty) -> vampire_false")
  (step_extra "u229" "normal_form" ("rule=flattening" "source=(Empty = Empty) -> vampire_false" "target=(Empty = Empty) -> vampire_false"))
  (step_extra "u229" "raw" ("number=1"))
  (step_proposition "u307" "(Empty = Empty) -> vampire_false")
  (step_extra "u307" "cnf" ("rule=cnf transformation" "parent_unit=229" "parent_kind=formula" "source=(Empty = Empty) -> vampire_false" "source_proposition=(Empty = Empty) -> vampire_false" "target=(Empty = Empty) -> vampire_false" "target_proposition=(Empty = Empty) -> vampire_false" "target_clause=[{\"polarity\":false,\"atom\":{\"eq\":[{\"const\":\"Empty\"},{\"const\":\"Empty\"}]}}]" "target_literal_count=1" "target_literal_0=(Empty = Empty) -> vampire_false" "parent_clause_count=1" "clause_parent_unit=229" "clause_index=0" "clause_count=1" "target_variable_sort_count=0"))
  (step_extra "u307" "raw" ("parent=229,index=0,count=1"))
  (step_proposition "u310" "vampire_false")
  (symbol_declaration "Variable Empty:set.")
  (formula_input "u78" (source conjecture "conj_c__2Fproject_2Ftmp_2Fsource_5Flinked_5Fstrict_5F100_5Fcorpus_5Ffresh_5F041947_2Fhammer_5F11560_5F31") (pos (AP (AP (TMH "=") (TMH "Empty")) (TMH "Empty"))))
  (formula_term_input "u79" (source negated_conjecture "conj_c__2Fproject_2Ftmp_2Fsource_5Flinked_5Fstrict_5F100_5Fcorpus_5Ffresh_5F041947_2Fhammer_5F11560_5F31") (formula (IMP (AP (AP (TMH "=") (TMH "Empty")) (TMH "Empty")) (TMH "vampire_false"))))
  (formula_copy "u229" (parent "u79") (result (neg (AP (AP (TMH "=") (TMH "Empty")) (TMH "Empty")))))
  (cnf_literal "u307" (parent "u229") (result (clause (neg (AP (AP (TMH "=") (TMH "Empty")) (TMH "Empty"))))))
  (equality_resolution "u310" (parent "u307") (literal 0) (result (clause)))
)
