(certificate vampire-megalodon 1
  (problem "vampire-native-certificate")
  (step_proposition "u9" "forall X0:set, In X0 (ordsucc X0)")
  (step_variable_sorts "u9" ("X0:set"))
  (step_proposition "u75" "SNoLev u = ordsucc n")
  (step_extra "u75" "raw" ("number=1"))
  (step_proposition "u76" "In n (SNoLev u)")
  (step_proposition "u77" "(In n (SNoLev u)) -> vampire_false")
  (step_proposition "u93" "forall X0:set, In X0 (ordsucc X0)")
  (step_variable_sorts "u93" ("X0:set"))
  (step_extra "u93" "rectify" ("rule=rectify" "source=forall X0:set, In X0 (ordsucc X0)" "target=forall X0:set, In X0 (ordsucc X0)" "renaming_count=1" "renaming_0_source=forall X0:set, In X0 (ordsucc X0)" "renaming_0_source_substituted=forall X0:set, In X0 (ordsucc X0)" "renaming_0_target=forall X0:set, In X0 (ordsucc X0)"))
  (step_proposition "u94" "forall X0:set, vampire_eq_prop (In X0 (ordsucc X0)) (vampire_true)")
  (step_variable_sorts "u94" ("X0:set"))
  (step_extra "u94" "fool" ("rule=fool elimination" "source=forall X0:set, In X0 (ordsucc X0)" "target=forall X0:set, vampire_eq_prop (In X0 (ordsucc X0)) (vampire_true)" "pair_0_source=forall X0:set, In X0 (ordsucc X0)" "pair_0_target=forall X0:set, vampire_eq_prop (In X0 (ordsucc X0)) (vampire_true)" "pair_1_source=In X0 (ordsucc X0)" "pair_1_target=vampire_eq_prop (In X0 (ordsucc X0)) (vampire_true)"))
  (step_extra "u94" "raw" ("number=1"))
  (step_proposition "u224" "(In n (SNoLev u)) -> vampire_false")
  (step_extra "u224" "rectify" ("rule=rectify" "source=(In n (SNoLev u)) -> vampire_false" "target=(In n (SNoLev u)) -> vampire_false" "renaming_count=0"))
  (step_proposition "u225" "(vampire_eq_prop (In n (SNoLev u)) (vampire_true)) -> vampire_false")
  (step_extra "u225" "fool" ("rule=fool elimination" "source=(In n (SNoLev u)) -> vampire_false" "target=(vampire_eq_prop (In n (SNoLev u)) (vampire_true)) -> vampire_false" "pair_0_source=(In n (SNoLev u)) -> vampire_false" "pair_0_target=(vampire_eq_prop (In n (SNoLev u)) (vampire_true)) -> vampire_false" "pair_1_source=In n (SNoLev u)" "pair_1_target=vampire_eq_prop (In n (SNoLev u)) (vampire_true)"))
  (step_proposition "u226" "(vampire_eq_prop (In n (SNoLev u)) (vampire_true)) -> vampire_false")
  (step_extra "u226" "normal_form" ("rule=flattening" "source=(vampire_eq_prop (In n (SNoLev u)) (vampire_true)) -> vampire_false" "target=(vampire_eq_prop (In n (SNoLev u)) (vampire_true)) -> vampire_false"))
  (step_extra "u226" "raw" ("number=1"))
  (step_proposition "u235" "forall X0:set, vampire_eq_prop (In X0 (ordsucc X0)) (vampire_true)")
  (step_variable_sorts "u235" ("X0:set"))
  (step_extra "u235" "cnf" ("rule=cnf transformation" "parent_unit=94" "parent_kind=formula" "source=forall X0:set, vampire_eq_prop (In X0 (ordsucc X0)) (vampire_true)" "source_proposition=forall X0:set, vampire_eq_prop (In X0 (ordsucc X0)) (vampire_true)" "target=forall X0:set, vampire_eq_prop (In X0 (ordsucc X0)) (vampire_true)" "target_proposition=forall X0:set, vampire_eq_prop (In X0 (ordsucc X0)) (vampire_true)" "target_clause=[{\"polarity\":true,\"atom\":{\"eq\":[{\"apply\":[{\"apply\":[{\"const\":\"In\"},{\"var\":\"X0\"}]},{\"apply\":[{\"const\":\"ordsucc\"},{\"var\":\"X0\"}]}]},{\"const\":\"f__true\"}],\"sort\":\"prop\"}}]" "target_literal_count=1" "target_literal_0=vampire_eq_prop (In X0 (ordsucc X0)) (vampire_true)" "parent_clause_count=1" "clause_parent_unit=94" "clause_index=0" "clause_count=1" "target_variable_sort_count=1" "target_variable_sort_0=X0:set"))
  (step_extra "u235" "raw" ("parent=94,index=0,count=1"))
  (step_proposition "u301" "SNoLev u = ordsucc n")
  (step_extra "u301" "cnf" ("rule=cnf transformation" "parent_unit=75" "parent_kind=formula" "source=SNoLev u = ordsucc n" "source_proposition=SNoLev u = ordsucc n" "target=SNoLev u = ordsucc n" "target_proposition=SNoLev u = ordsucc n" "target_clause=[{\"polarity\":true,\"atom\":{\"eq\":[{\"apply\":[{\"const\":\"SNoLev\"},{\"const\":\"u\"}]},{\"apply\":[{\"const\":\"ordsucc\"},{\"const\":\"n\"}]}]}}]" "target_literal_count=1" "target_literal_0=SNoLev u = ordsucc n" "parent_clause_count=1" "clause_parent_unit=75" "clause_index=0" "clause_count=1" "target_variable_sort_count=0"))
  (step_extra "u301" "raw" ("parent=75,index=0,count=1"))
  (step_proposition "u302" "(vampire_eq_prop (In n (SNoLev u)) (vampire_true)) -> vampire_false")
  (step_extra "u302" "cnf" ("rule=cnf transformation" "parent_unit=226" "parent_kind=formula" "source=(vampire_eq_prop (In n (SNoLev u)) (vampire_true)) -> vampire_false" "source_proposition=(vampire_eq_prop (In n (SNoLev u)) (vampire_true)) -> vampire_false" "target=(vampire_eq_prop (In n (SNoLev u)) (vampire_true)) -> vampire_false" "target_proposition=(vampire_eq_prop (In n (SNoLev u)) (vampire_true)) -> vampire_false" "target_clause=[{\"polarity\":false,\"atom\":{\"eq\":[{\"apply\":[{\"apply\":[{\"const\":\"In\"},{\"const\":\"n\"}]},{\"apply\":[{\"const\":\"SNoLev\"},{\"const\":\"u\"}]}]},{\"const\":\"f__true\"}],\"sort\":\"prop\"}}]" "target_literal_count=1" "target_literal_0=(vampire_eq_prop (In n (SNoLev u)) (vampire_true)) -> vampire_false" "parent_clause_count=1" "clause_parent_unit=226" "clause_index=0" "clause_count=1" "target_variable_sort_count=0"))
  (step_extra "u302" "raw" ("parent=226,index=0,count=1"))
  (step_proposition "u305" "vampire_eq_set_to_prop (In n) (sF0)")
  (step_extra "u305" "function_definition" ("introduced_symbol=sF0" "sort=set->prop" "equality_sort=set->prop" "lhs=In n" "rhs=sF0" "proposition=vampire_eq_set_to_prop (In n) (sF0)"))
  (step_extra "u305" "clause_equality" ("equality_sort=set->prop" "lhs=In n" "rhs=sF0" "proposition=In n = sF0"))
  (step_proposition "u306" "SNoLev u = sF1")
  (step_extra "u306" "function_definition" ("introduced_symbol=sF1" "sort=set" "equality_sort=set" "lhs=SNoLev u" "rhs=sF1" "proposition=SNoLev u = sF1"))
  (step_proposition "u307" "vampire_eq_prop (sF0 sF1) (sF2)")
  (step_extra "u307" "function_definition" ("introduced_symbol=sF2" "sort=prop" "equality_sort=prop" "lhs=sF0 sF1" "rhs=sF2" "proposition=vampire_eq_prop (sF0 sF1) (sF2)"))
  (step_proposition "u308" "(vampire_eq_prop (vampire_true) (sF2)) -> vampire_false")
  (step_extra "u308" "definition_rewrite" ("rule=definition folding" "target=(vampire_eq_prop (vampire_true) (sF2)) -> vampire_false" "parent_0=(vampire_eq_prop (In n (SNoLev u)) (vampire_true)) -> vampire_false" "source=(vampire_eq_prop (In n (SNoLev u)) (vampire_true)) -> vampire_false" "parent_1=vampire_eq_prop (sF0 sF1) (sF2)" "definition=vampire_eq_prop (sF0 sF1) (sF2)" "parent_2=SNoLev u = sF1" "parent_3=vampire_eq_set_to_prop (In n) (sF0)" "fold_step_count=3" "fold_step_0_lhs=In n" "fold_step_0_rhs=sF0" "fold_step_0_literal=0" "fold_step_0_position=0.2" "fold_step_1_lhs=SNoLev u" "fold_step_1_rhs=sF1" "fold_step_1_literal=0" "fold_step_1_position=0.3" "fold_step_2_lhs=sF0 sF1" "fold_step_2_rhs=sF2" "fold_step_2_literal=0" "fold_step_2_position=0"))
  (step_extra "u308" "raw" ("steps=3,step0=(c_In @ n -> sF0)@0:0.2,step1=(c_SNoLev @ u -> sF1)@0:0.3,step2=(sF0 @ sF1 -> sF2)@0:0"))
  (step_proposition "u334" "ordsucc n = sF1")
  (step_extra "u334" "two_literal_rewrite" ("selected=(((c_SNoLev @ u)) = sF1)" "other=(((c_SNoLev @ u)) = ((ordsucc @ n)))" "selected_parent_index=0" "selected_literal_index=0" "selected_parent_unit=306" "selected_substituted=(((c_SNoLev @ u)) = sF1)" "selected_substituted_db_indices=(((c_SNoLev @ u)) = sF1)" "selected_substituted_proposition=SNoLev u = sF1" "other_parent_index=1" "other_literal_index=0" "other_parent_unit=301" "other_substituted=(((c_SNoLev @ u)) = ((ordsucc @ n)))" "other_substituted_db_indices=(((c_SNoLev @ u)) = ((ordsucc @ n)))" "other_substituted_proposition=SNoLev u = ordsucc n" "lhs=c_SNoLev @ u" "target=c_SNoLev @ u" "lhs_term=SNoLev u" "target_term=SNoLev u" "lhs_sort=set" "target_sort=set" "parent_0_substitution=[0 -> X0]" "parent_0_substituted_clause=cnf(u306_subst,axiom,\n    (((c_SNoLev @ u)) = sF1)).\n" "parent_0_substituted_clause_db_indices=cnf(u306_subst,axiom,\n    (((c_SNoLev @ u)) = sF1)).\n" "parent_1_substitution=[0 -> X1]" "parent_1_substituted_clause=cnf(u301_subst,axiom,\n    (((c_SNoLev @ u)) = ((ordsucc @ n)))).\n" "parent_1_substituted_clause_db_indices=cnf(u301_subst,axiom,\n    (((c_SNoLev @ u)) = ((ordsucc @ n)))).\n"))
  (step_proposition "u529" "vampire_eq_prop (vampire_true) (In n sF1)")
  (step_extra "u529" "two_literal_rewrite" ("selected=(((c_In @ X0 @ (ordsucc @ X0))) = $true)" "other=(((ordsucc @ n)) = sF1)" "selected_parent_index=0" "selected_literal_index=0" "selected_parent_unit=235" "selected_substituted=($true = ((c_In @ n @ (ordsucc @ n))))" "selected_substituted_db_indices=($true = ((c_In @ n @ (ordsucc @ n))))" "selected_substituted_proposition=vampire_eq_prop (vampire_true) (In n (ordsucc n))" "other_parent_index=1" "other_literal_index=0" "other_parent_unit=334" "other_substituted=(((ordsucc @ n)) = sF1)" "other_substituted_db_indices=(((ordsucc @ n)) = sF1)" "other_substituted_proposition=ordsucc n = sF1" "lhs=ordsucc @ n" "target=ordsucc @ X0" "lhs_term=ordsucc n" "target_term=ordsucc X0" "lhs_sort=set" "target_sort=set" "parent_0_substitution=[0 -> n]" "parent_0_substituted_clause=cnf(u235_subst,axiom,\n    ($true = ((c_In @ n @ (ordsucc @ n))))).\n" "parent_0_substituted_clause_db_indices=cnf(u235_subst,axiom,\n    ($true = ((c_In @ n @ (ordsucc @ n))))).\n" "parent_1_substitution=[0 -> X0]" "parent_1_substituted_clause=cnf(u334_subst,axiom,\n    (((ordsucc @ n)) = sF1)).\n" "parent_1_substituted_clause_db_indices=cnf(u334_subst,axiom,\n    (((ordsucc @ n)) = sF1)).\n"))
  (step_proposition "u545" "vampire_eq_prop (vampire_true) (sF0 sF1)")
  (step_extra "u545" "rewrite" ("lhs=c_In @ n" "target=c_In @ n" "rule_lhs=In n" "redex=In n" "rule_rhs=sF0" "replacement=sF0" "rule_lhs=In n" "rule_rhs=sF0" "redex=In n" "replacement=sF0" "parent_0_substitution=[]" "parent_0_substituted_clause=cnf(u529_subst,axiom,\n    ($true = ((c_In @ n @ sF1)))).\n" "parent_0_substituted_clause_db_indices=cnf(u529_subst,axiom,\n    ($true = ((c_In @ n @ sF1)))).\n" "parent_1_substitution=[]" "parent_1_substituted_clause=cnf(u305_subst,axiom,\n    (((c_In @ n)) = sF0)).\n" "parent_1_substituted_clause_db_indices=cnf(u305_subst,axiom,\n    (((c_In @ n)) = sF0)).\n"))
  (step_proposition "u557" "vampire_eq_prop (vampire_true) (sF2)")
  (step_extra "u557" "two_literal_rewrite" ("selected=(((sF0 @ sF1)) = sF2)" "other=($true = ((sF0 @ sF1)))" "selected_parent_index=0" "selected_literal_index=0" "selected_parent_unit=307" "selected_substituted=(((sF0 @ sF1)) = sF2)" "selected_substituted_db_indices=(((sF0 @ sF1)) = sF2)" "selected_substituted_proposition=vampire_eq_prop (sF0 sF1) (sF2)" "other_parent_index=1" "other_literal_index=0" "other_parent_unit=545" "other_substituted=($true = ((sF0 @ sF1)))" "other_substituted_db_indices=($true = ((sF0 @ sF1)))" "other_substituted_proposition=vampire_eq_prop (vampire_true) (sF0 sF1)" "lhs=sF0 @ sF1" "target=sF0 @ sF1" "lhs_term=sF0 sF1" "target_term=sF0 sF1" "lhs_sort=prop" "target_sort=prop" "parent_0_substitution=[0 -> X0]" "parent_0_substituted_clause=cnf(u307_subst,axiom,\n    (((sF0 @ sF1)) = sF2)).\n" "parent_0_substituted_clause_db_indices=cnf(u307_subst,axiom,\n    (((sF0 @ sF1)) = sF2)).\n" "parent_1_substitution=[0 -> X1]" "parent_1_substituted_clause=cnf(u545_subst,axiom,\n    ($true = ((sF0 @ sF1)))).\n" "parent_1_substituted_clause_db_indices=cnf(u545_subst,axiom,\n    ($true = ((sF0 @ sF1)))).\n"))
  (step_proposition "u560" "vampire_false")
  (step_extra "u560" "literal" ("selected=($true = sF2)" "selected_parent_index=0" "selected_literal_index=0" "selected_parent_unit=557" "selected_substitution_source=sat_subsumption" "selected_substitution=[]" "selected_substituted=($true = sF2)" "selected_substituted_db_indices=($true = sF2)" "selected_substituted_proposition=vampire_eq_prop (vampire_true) (sF2)"))
  (symbol_declaration "Variable In:set->set->prop.")
  (symbol_declaration "Variable ordsucc:set->set.")
  (symbol_declaration "Variable SNoLev:set->set.")
  (symbol_declaration "Variable n:set.")
  (symbol_declaration "Variable u:set.")
  (symbol_declaration "Variable f__true:prop.")
  (symbol_declaration "Variable sF0:set->prop.")
  (symbol_declaration "Variable sF1:set.")
  (symbol_declaration "Variable sF2:prop.")
  (formula_term_input "u9" (source axiom "ordsuccI2") (formula (ALL (SET) (AP (AP (TMH "In") (TMH "X0")) (AP (TMH "ordsucc") (TMH "X0"))))))
  (formula_input "u75" (source axiom "c_Hu0b") (pos (AP (AP (TMH "=") (AP (TMH "SNoLev") (TMH "u"))) (AP (TMH "ordsucc") (TMH "n")))))
  (formula_input "u76" (source conjecture "conj_c__2Fproject_2Ftmp_2Fsource_5Flinked_5Fstrict_5F100_5Fcorpus_5Ffresh_5F041947_2Fhammer_5F11669_5F25") (pos (AP (AP (TMH "In") (TMH "n")) (AP (TMH "SNoLev") (TMH "u")))))
  (formula_term_input "u77" (source negated_conjecture "conj_c__2Fproject_2Ftmp_2Fsource_5Flinked_5Fstrict_5F100_5Fcorpus_5Ffresh_5F041947_2Fhammer_5F11669_5F25") (formula (IMP (AP (AP (TMH "In") (TMH "n")) (AP (TMH "SNoLev") (TMH "u"))) (TMH "vampire_false"))))
  (rectify_formula "u93" (parent "u9") (renamings (renaming (source (formula (ALL (SET) (AP (AP (TMH "In") (TMH "X0")) (AP (TMH "ordsucc") (TMH "X0")))))) (subst) (target (formula (ALL (SET) (AP (AP (TMH "In") (TMH "X0")) (AP (TMH "ordsucc") (TMH "X0")))))))) (result (formula (ALL (SET) (AP (AP (TMH "In") (TMH "X0")) (AP (TMH "ordsucc") (TMH "X0")))))))
  (fool_formula "u94" (parent "u93") (result (formula (ALL (SET) (AP (AP (TMH "=") (AP (AP (TMH "In") (TMH "X0")) (AP (TMH "ordsucc") (TMH "X0")))) (TMH "f__true"))))))
  (rectify_formula "u224" (parent "u77") (result (formula (IMP (AP (AP (TMH "In") (TMH "n")) (AP (TMH "SNoLev") (TMH "u"))) (TMH "vampire_false")))))
  (fool_bool "u225" (parent "u224") (result (neg (AP (AP (TMH "=") (AP (AP (TMH "In") (TMH "n")) (AP (TMH "SNoLev") (TMH "u")))) (TMH "f__true")))))
  (formula_copy "u226" (parent "u225") (result (neg (AP (AP (TMH "=") (AP (AP (TMH "In") (TMH "n")) (AP (TMH "SNoLev") (TMH "u")))) (TMH "f__true")))))
  (cnf_formula_clause "u235" (parent "u94") (index 0) (result (clause (pos (AP (AP (TMH "=") (AP (AP (TMH "In") (TMH "X0")) (AP (TMH "ordsucc") (TMH "X0")))) (TMH "f__true"))))))
  (cnf_literal "u301" (parent "u75") (result (clause (pos (AP (AP (TMH "=") (AP (TMH "SNoLev") (TMH "u"))) (AP (TMH "ordsucc") (TMH "n")))))))
  (cnf_literal "u302" (parent "u226") (result (clause (neg (AP (AP (TMH "=") (AP (AP (TMH "In") (TMH "n")) (AP (TMH "SNoLev") (TMH "u")))) (TMH "f__true"))))))
  (definition_input "u305" (result (clause (pos (AP (AP (TMH "=") (AP (TMH "In") (TMH "n"))) (TMH "sF0"))))))
  (definition_input "u306" (result (clause (pos (AP (AP (TMH "=") (AP (TMH "SNoLev") (TMH "u"))) (TMH "sF1"))))))
  (definition_input "u307" (result (clause (pos (AP (AP (TMH "=") (AP (TMH "sF0") (TMH "sF1"))) (TMH "sF2"))))))
  (paramodulate "u308_paramodulate0" (equality "u305" 0) (target "u302" 0) (position 0 1 0) (from (AP (TMH "In") (TMH "n"))) (to (TMH "sF0")) (result (clause (neg (AP (AP (TMH "=") (TMH "f__true")) (AP (TMH "sF0") (AP (TMH "SNoLev") (TMH "u"))))))))
  (paramodulate "u308_paramodulate1" (equality "u306" 0) (target "u308_paramodulate0" 0) (position 1 1) (from (AP (TMH "SNoLev") (TMH "u"))) (to (TMH "sF1")) (result (clause (neg (AP (AP (TMH "=") (TMH "f__true")) (AP (TMH "sF0") (TMH "sF1")))))))
  (paramodulate "u308" (equality "u307" 0) (target "u308_paramodulate1" 0) (position 1) (from (AP (TMH "sF0") (TMH "sF1"))) (to (TMH "sF2")) (result (clause (neg (AP (AP (TMH "=") (TMH "f__true")) (TMH "sF2"))))))
  (substitute "u334_subst0" (parent "u306") (subst) (result (clause (pos (AP (AP (TMH "=") (AP (TMH "SNoLev") (TMH "u"))) (TMH "sF1"))))))
  (substitute "u334_subst1" (parent "u301") (subst ("X0" (TMH "X1"))) (result (clause (pos (AP (AP (TMH "=") (AP (TMH "SNoLev") (TMH "u"))) (AP (TMH "ordsucc") (TMH "n")))))))
  (paramodulate "u334" (equality "u334_subst1" 0) (target "u334_subst0" 0) (position 0 1) (from (AP (TMH "SNoLev") (TMH "u"))) (to (AP (TMH "ordsucc") (TMH "n"))) (result (clause (pos (AP (AP (TMH "=") (AP (TMH "ordsucc") (TMH "n"))) (TMH "sF1"))))))
  (substitute "u529_subst0" (parent "u235") (subst ("X0" (TMH "n"))) (result (clause (pos (AP (AP (TMH "=") (AP (AP (TMH "In") (TMH "n")) (AP (TMH "ordsucc") (TMH "n")))) (TMH "f__true"))))))
  (substitute "u529_subst1" (parent "u334") (subst) (result (clause (pos (AP (AP (TMH "=") (AP (TMH "ordsucc") (TMH "n"))) (TMH "sF1"))))))
  (paramodulate "u529" (equality "u529_subst1" 0) (target "u529_subst0" 0) (position 1 1) (from (AP (TMH "ordsucc") (TMH "n"))) (to (TMH "sF1")) (result (clause (pos (AP (AP (TMH "=") (TMH "f__true")) (AP (AP (TMH "In") (TMH "n")) (TMH "sF1")))))))
  (paramodulate "u545" (equality "u305" 0) (target "u529" 0) (position 1 0) (from (AP (TMH "In") (TMH "n"))) (to (TMH "sF0")) (result (clause (pos (AP (AP (TMH "=") (TMH "f__true")) (AP (TMH "sF0") (TMH "sF1")))))))
  (substitute "u557_subst0" (parent "u307") (subst) (result (clause (pos (AP (AP (TMH "=") (AP (TMH "sF0") (TMH "sF1"))) (TMH "sF2"))))))
  (substitute "u557_subst1" (parent "u545") (subst ("X0" (TMH "X1"))) (result (clause (pos (AP (AP (TMH "=") (TMH "f__true")) (AP (TMH "sF0") (TMH "sF1")))))))
  (paramodulate "u557" (equality "u557_subst1" 0) (target "u557_subst0" 0) (position 0 1) (from (AP (TMH "sF0") (TMH "sF1"))) (to (TMH "f__true")) (result (clause (pos (AP (AP (TMH "=") (TMH "f__true")) (TMH "sF2"))))))
  (resolve "u560" (parents "u557" "u308") (pivot 0 0) (result (clause)))
)
