(certificate vampire-megalodon 1
  (problem "vampire-native-certificate")
  (step_proposition "u68" "In (add_SNo n (minus_SNo r)) n")
  (step_proposition "u91" "In (add_SNo n (minus_SNo r)) n")
  (step_proposition "u92" "(In (add_SNo n (minus_SNo r)) n) -> vampire_false")
  (step_proposition "u225" "In (add_SNo n (minus_SNo r)) n")
  (step_extra "u225" "rectify" ("rule=rectify" "source=In (add_SNo n (minus_SNo r)) n" "target=In (add_SNo n (minus_SNo r)) n" "renaming_count=0"))
  (step_proposition "u226" "vampire_eq_prop (In (add_SNo n (minus_SNo r)) n) (vampire_true)")
  (step_extra "u226" "fool" ("rule=fool elimination" "source=In (add_SNo n (minus_SNo r)) n" "target=vampire_eq_prop (In (add_SNo n (minus_SNo r)) n) (vampire_true)" "pair_0_source=In (add_SNo n (minus_SNo r)) n" "pair_0_target=vampire_eq_prop (In (add_SNo n (minus_SNo r)) n) (vampire_true)"))
  (step_extra "u226" "raw" ("number=1"))
  (step_proposition "u267" "(In (add_SNo n (minus_SNo r)) n) -> vampire_false")
  (step_extra "u267" "rectify" ("rule=rectify" "source=(In (add_SNo n (minus_SNo r)) n) -> vampire_false" "target=(In (add_SNo n (minus_SNo r)) n) -> vampire_false" "renaming_count=0"))
  (step_proposition "u268" "(vampire_eq_prop (In (add_SNo n (minus_SNo r)) n) (vampire_true)) -> vampire_false")
  (step_extra "u268" "fool" ("rule=fool elimination" "source=(In (add_SNo n (minus_SNo r)) n) -> vampire_false" "target=(vampire_eq_prop (In (add_SNo n (minus_SNo r)) n) (vampire_true)) -> vampire_false" "pair_0_source=(In (add_SNo n (minus_SNo r)) n) -> vampire_false" "pair_0_target=(vampire_eq_prop (In (add_SNo n (minus_SNo r)) n) (vampire_true)) -> vampire_false" "pair_1_source=In (add_SNo n (minus_SNo r)) n" "pair_1_target=vampire_eq_prop (In (add_SNo n (minus_SNo r)) n) (vampire_true)"))
  (step_proposition "u269" "(vampire_eq_prop (In (add_SNo n (minus_SNo r)) n) (vampire_true)) -> vampire_false")
  (step_extra "u269" "normal_form" ("rule=flattening" "source=(vampire_eq_prop (In (add_SNo n (minus_SNo r)) n) (vampire_true)) -> vampire_false" "target=(vampire_eq_prop (In (add_SNo n (minus_SNo r)) n) (vampire_true)) -> vampire_false"))
  (step_extra "u269" "raw" ("number=1"))
  (step_proposition "u285" "(vampire_eq_prop (In (add_SNo n (minus_SNo r)) n) (vampire_true)) -> vampire_false")
  (step_extra "u285" "cnf" ("rule=cnf transformation" "parent_unit=269" "parent_kind=formula" "source=(vampire_eq_prop (In (add_SNo n (minus_SNo r)) n) (vampire_true)) -> vampire_false" "source_proposition=(vampire_eq_prop (In (add_SNo n (minus_SNo r)) n) (vampire_true)) -> vampire_false" "target=(vampire_eq_prop (In (add_SNo n (minus_SNo r)) n) (vampire_true)) -> vampire_false" "target_proposition=(vampire_eq_prop (In (add_SNo n (minus_SNo r)) n) (vampire_true)) -> vampire_false" "target_clause=[{\"polarity\":false,\"atom\":{\"eq\":[{\"apply\":[{\"apply\":[{\"const\":\"In\"},{\"apply\":[{\"apply\":[{\"const\":\"add_SNo\"},{\"const\":\"n\"}]},{\"apply\":[{\"const\":\"minus_SNo\"},{\"const\":\"r\"}]}]}]},{\"const\":\"n\"}]},{\"const\":\"f__true\"}],\"sort\":\"prop\"}}]" "target_literal_count=1" "target_literal_0=(vampire_eq_prop (In (add_SNo n (minus_SNo r)) n) (vampire_true)) -> vampire_false" "parent_clause_count=1" "clause_parent_unit=269" "clause_index=0" "clause_count=1" "target_variable_sort_count=0"))
  (step_extra "u285" "raw" ("parent=269,index=0,count=1"))
  (step_proposition "u286" "vampire_eq_prop (In (add_SNo n (minus_SNo r)) n) (vampire_true)")
  (step_extra "u286" "cnf" ("rule=cnf transformation" "parent_unit=226" "parent_kind=formula" "source=vampire_eq_prop (In (add_SNo n (minus_SNo r)) n) (vampire_true)" "source_proposition=vampire_eq_prop (In (add_SNo n (minus_SNo r)) n) (vampire_true)" "target=vampire_eq_prop (In (add_SNo n (minus_SNo r)) n) (vampire_true)" "target_proposition=vampire_eq_prop (In (add_SNo n (minus_SNo r)) n) (vampire_true)" "target_clause=[{\"polarity\":true,\"atom\":{\"eq\":[{\"apply\":[{\"apply\":[{\"const\":\"In\"},{\"apply\":[{\"apply\":[{\"const\":\"add_SNo\"},{\"const\":\"n\"}]},{\"apply\":[{\"const\":\"minus_SNo\"},{\"const\":\"r\"}]}]}]},{\"const\":\"n\"}]},{\"const\":\"f__true\"}],\"sort\":\"prop\"}}]" "target_literal_count=1" "target_literal_0=vampire_eq_prop (In (add_SNo n (minus_SNo r)) n) (vampire_true)" "parent_clause_count=1" "clause_parent_unit=226" "clause_index=0" "clause_count=1" "target_variable_sort_count=0"))
  (step_extra "u286" "raw" ("parent=226,index=0,count=1"))
  (step_proposition "u321" "vampire_false")
  (step_extra "u321" "literal" ("selected=(((c_In @ (add_5FSNo @ n @ (minus_5FSNo @ r)) @ n)) != $true)" "selected_parent_index=0" "selected_literal_index=0" "selected_parent_unit=285" "selected_substitution_source=sat_subsumption" "selected_substitution=[]" "selected_substituted=(((c_In @ (add_5FSNo @ n @ (minus_5FSNo @ r)) @ n)) != $true)" "selected_substituted_db_indices=(((c_In @ (add_5FSNo @ n @ (minus_5FSNo @ r)) @ n)) != $true)" "selected_substituted_proposition=(vampire_eq_prop (In (add_SNo n (minus_SNo r)) n) (vampire_true)) -> vampire_false"))
  (symbol_declaration "Variable In:set->set->prop.")
  (symbol_declaration "Variable minus_SNo:set->set.")
  (symbol_declaration "Variable add_SNo:set->set->set.")
  (symbol_declaration "Variable n:set.")
  (symbol_declaration "Variable r:set.")
  (symbol_declaration "Variable f__true:prop.")
  (formula_input "u68" (source axiom "c_L4") (pos (AP (AP (TMH "In") (AP (AP (TMH "add_SNo") (TMH "n")) (AP (TMH "minus_SNo") (TMH "r")))) (TMH "n"))))
  (formula_input "u91" (source conjecture "conj_c__2Fproject_2Ftmp_2Fsource_5Flinked_5Fstrict_5F100_5Fcorpus_5Ffresh_5F041947_2Fhammer_5F10809_5F92") (pos (AP (AP (TMH "In") (AP (AP (TMH "add_SNo") (TMH "n")) (AP (TMH "minus_SNo") (TMH "r")))) (TMH "n"))))
  (formula_term_input "u92" (source negated_conjecture "conj_c__2Fproject_2Ftmp_2Fsource_5Flinked_5Fstrict_5F100_5Fcorpus_5Ffresh_5F041947_2Fhammer_5F10809_5F92") (formula (IMP (AP (AP (TMH "In") (AP (AP (TMH "add_SNo") (TMH "n")) (AP (TMH "minus_SNo") (TMH "r")))) (TMH "n")) (TMH "vampire_false"))))
  (rectify_formula "u225" (parent "u68") (result (formula (AP (AP (TMH "In") (AP (AP (TMH "add_SNo") (TMH "n")) (AP (TMH "minus_SNo") (TMH "r")))) (TMH "n")))))
  (fool_bool "u226" (parent "u225") (result (pos (AP (AP (TMH "=") (AP (AP (TMH "In") (AP (AP (TMH "add_SNo") (TMH "n")) (AP (TMH "minus_SNo") (TMH "r")))) (TMH "n"))) (TMH "f__true")))))
  (rectify_formula "u267" (parent "u92") (result (formula (IMP (AP (AP (TMH "In") (AP (AP (TMH "add_SNo") (TMH "n")) (AP (TMH "minus_SNo") (TMH "r")))) (TMH "n")) (TMH "vampire_false")))))
  (fool_bool "u268" (parent "u267") (result (neg (AP (AP (TMH "=") (AP (AP (TMH "In") (AP (AP (TMH "add_SNo") (TMH "n")) (AP (TMH "minus_SNo") (TMH "r")))) (TMH "n"))) (TMH "f__true")))))
  (formula_copy "u269" (parent "u268") (result (neg (AP (AP (TMH "=") (AP (AP (TMH "In") (AP (AP (TMH "add_SNo") (TMH "n")) (AP (TMH "minus_SNo") (TMH "r")))) (TMH "n"))) (TMH "f__true")))))
  (cnf_literal "u285" (parent "u269") (result (clause (neg (AP (AP (TMH "=") (AP (AP (TMH "In") (AP (AP (TMH "add_SNo") (TMH "n")) (AP (TMH "minus_SNo") (TMH "r")))) (TMH "n"))) (TMH "f__true"))))))
  (cnf_literal "u286" (parent "u226") (result (clause (pos (AP (AP (TMH "=") (AP (AP (TMH "In") (AP (AP (TMH "add_SNo") (TMH "n")) (AP (TMH "minus_SNo") (TMH "r")))) (TMH "n"))) (TMH "f__true"))))))
  (resolve "u321" (parents "u285" "u286") (pivot 0 0) (result (clause)))
)
