(certificate vampire-megalodon 1
  (problem "vampire-native-certificate")
  (step_proposition "u82" "In q omega")
  (step_proposition "u91" "In q omega")
  (step_proposition "u92" "(In q omega) -> vampire_false")
  (step_proposition "u249" "In q omega")
  (step_extra "u249" "rectify" ("rule=rectify" "source=In q omega" "target=In q omega" "renaming_count=0"))
  (step_proposition "u250" "vampire_eq_prop (In q omega) (vampire_true)")
  (step_extra "u250" "fool" ("rule=fool elimination" "source=In q omega" "target=vampire_eq_prop (In q omega) (vampire_true)" "pair_0_source=In q omega" "pair_0_target=vampire_eq_prop (In q omega) (vampire_true)"))
  (step_extra "u250" "raw" ("number=1"))
  (step_proposition "u267" "(In q omega) -> vampire_false")
  (step_extra "u267" "rectify" ("rule=rectify" "source=(In q omega) -> vampire_false" "target=(In q omega) -> vampire_false" "renaming_count=0"))
  (step_proposition "u268" "(vampire_eq_prop (In q omega) (vampire_true)) -> vampire_false")
  (step_extra "u268" "fool" ("rule=fool elimination" "source=(In q omega) -> vampire_false" "target=(vampire_eq_prop (In q omega) (vampire_true)) -> vampire_false" "pair_0_source=(In q omega) -> vampire_false" "pair_0_target=(vampire_eq_prop (In q omega) (vampire_true)) -> vampire_false" "pair_1_source=In q omega" "pair_1_target=vampire_eq_prop (In q omega) (vampire_true)"))
  (step_proposition "u270" "(vampire_eq_prop (In q omega) (vampire_true)) -> vampire_false")
  (step_extra "u270" "normal_form" ("rule=flattening" "source=(vampire_eq_prop (In q omega) (vampire_true)) -> vampire_false" "target=(vampire_eq_prop (In q omega) (vampire_true)) -> vampire_false"))
  (step_extra "u270" "raw" ("number=1"))
  (step_proposition "u397" "vampire_eq_prop (In q omega) (vampire_true)")
  (step_extra "u397" "cnf" ("rule=cnf transformation" "parent_unit=250" "parent_kind=formula" "source=vampire_eq_prop (In q omega) (vampire_true)" "source_proposition=vampire_eq_prop (In q omega) (vampire_true)" "target=vampire_eq_prop (In q omega) (vampire_true)" "target_proposition=vampire_eq_prop (In q omega) (vampire_true)" "target_clause=[{\"polarity\":true,\"atom\":{\"eq\":[{\"apply\":[{\"apply\":[{\"const\":\"In\"},{\"const\":\"q\"}]},{\"const\":\"omega\"}]},{\"const\":\"f__true\"}],\"sort\":\"prop\"}}]" "target_literal_count=1" "target_literal_0=vampire_eq_prop (In q omega) (vampire_true)" "parent_clause_count=1" "clause_parent_unit=250" "clause_index=0" "clause_count=1" "target_variable_sort_count=0"))
  (step_extra "u397" "raw" ("parent=250,index=0,count=1"))
  (step_proposition "u414" "(vampire_eq_prop (In q omega) (vampire_true)) -> vampire_false")
  (step_extra "u414" "cnf" ("rule=cnf transformation" "parent_unit=270" "parent_kind=formula" "source=(vampire_eq_prop (In q omega) (vampire_true)) -> vampire_false" "source_proposition=(vampire_eq_prop (In q omega) (vampire_true)) -> vampire_false" "target=(vampire_eq_prop (In q omega) (vampire_true)) -> vampire_false" "target_proposition=(vampire_eq_prop (In q omega) (vampire_true)) -> vampire_false" "target_clause=[{\"polarity\":false,\"atom\":{\"eq\":[{\"apply\":[{\"apply\":[{\"const\":\"In\"},{\"const\":\"q\"}]},{\"const\":\"omega\"}]},{\"const\":\"f__true\"}],\"sort\":\"prop\"}}]" "target_literal_count=1" "target_literal_0=(vampire_eq_prop (In q omega) (vampire_true)) -> vampire_false" "parent_clause_count=1" "clause_parent_unit=270" "clause_index=0" "clause_count=1" "target_variable_sort_count=0"))
  (step_extra "u414" "raw" ("parent=270,index=0,count=1"))
  (step_proposition "u428" "vampire_eq_set_to_prop (In q) (sF6)")
  (step_extra "u428" "function_definition" ("introduced_symbol=sF6" "sort=set->prop" "equality_sort=set->prop" "lhs=In q" "rhs=sF6" "proposition=vampire_eq_set_to_prop (In q) (sF6)"))
  (step_extra "u428" "clause_equality" ("equality_sort=set->prop" "lhs=In q" "rhs=sF6" "proposition=In q = sF6"))
  (step_proposition "u429" "vampire_eq_prop (sF6 omega) (sF7)")
  (step_extra "u429" "function_definition" ("introduced_symbol=sF7" "sort=prop" "equality_sort=prop" "lhs=sF6 omega" "rhs=sF7" "proposition=vampire_eq_prop (sF6 omega) (sF7)"))
  (step_proposition "u430" "(vampire_eq_prop (vampire_true) (sF7)) -> vampire_false")
  (step_extra "u430" "definition_rewrite" ("rule=definition folding" "target=(vampire_eq_prop (vampire_true) (sF7)) -> vampire_false" "parent_0=(vampire_eq_prop (In q omega) (vampire_true)) -> vampire_false" "source=(vampire_eq_prop (In q omega) (vampire_true)) -> vampire_false" "parent_1=vampire_eq_prop (sF6 omega) (sF7)" "definition=vampire_eq_prop (sF6 omega) (sF7)" "parent_2=vampire_eq_set_to_prop (In q) (sF6)" "fold_step_count=2" "fold_step_0_lhs=In q" "fold_step_0_rhs=sF6" "fold_step_0_literal=0" "fold_step_0_position=0.2" "fold_step_1_lhs=sF6 omega" "fold_step_1_rhs=sF7" "fold_step_1_literal=0" "fold_step_1_position=0"))
  (step_extra "u430" "raw" ("steps=2,step0=(c_In @ q -> sF6)@0:0.2,step1=(sF6 @ omega -> sF7)@0:0"))
  (step_proposition "u448" "vampire_and ((split_5) -> vampire_eq_prop (In q omega) (vampire_true)) ((vampire_eq_prop (In q omega) (vampire_true)) -> split_5)")
  (step_extra "u448" "avatar_definition" ("component_split_level=8" "component_split_var=5" "component_split_positive=1" "component_clause=vampire_or (vampire_eq_prop (In q omega) (vampire_true)) ((split_5) -> vampire_false)" "component_clause_variable_sort_count=0" "component_clause_db_sort_count=0"))
  (step_extra "u448" "raw" ("450"))
  (step_proposition "u450" "vampire_or (vampire_eq_prop (In q omega) (vampire_true)) ((split_5) -> vampire_false)")
  (step_extra "u450" "split_dependency" ("dependency_0_split_level=8" "dependency_0_split_var=5" "dependency_0_split_positive=1" "dependency_0_component_clause=vampire_or (vampire_eq_prop (In q omega) (vampire_true)) ((split_5) -> vampire_false)" "dependency_0_component_clause_variable_sort_count=0" "dependency_0_component_clause_db_sort_count=0" "dependency_count=1"))
  (step_proposition "u460" "split_5")
  (step_extra "u460" "avatar_split" ("rule=avatar split clause" "source=vampire_eq_prop (In q omega) (vampire_true)" "target=split_5" "previous_split_count=0" "sat_literal_0_var=5" "sat_literal_0_positive=1" "sat_literal_count=1" "component_parent_1_unit=448" "component_parent_1_split_level=8" "component_parent_1_split_var=5" "component_parent_1_split_positive=1" "component_parent_1_clause=vampire_or (vampire_eq_prop (In q omega) (vampire_true)) ((split_5) -> vampire_false)" "component_parent_count=1" "literal_class_0_literal_count=1" "literal_class_0_literal_0=vampire_eq_prop (In q omega) (vampire_true)" "literal_class_0_matched_split_level=8" "literal_class_count=1" "parent_var_binding_count=0"))
  (step_extra "u460" "raw" ("sat_clause_recorded"))
  (step_proposition "u510" "vampire_or (vampire_eq_prop (vampire_true) (sF6 omega)) ((split_5) -> vampire_false)")
  (step_extra "u510" "split_dependency" ("dependency_0_split_level=8" "dependency_0_split_var=5" "dependency_0_split_positive=1" "dependency_0_component_clause=vampire_or (vampire_eq_prop (In q omega) (vampire_true)) ((split_5) -> vampire_false)" "dependency_0_component_clause_variable_sort_count=0" "dependency_0_component_clause_db_sort_count=0" "dependency_count=1"))
  (step_extra "u510" "rewrite" ("lhs=c_In @ q" "target=c_In @ q" "rule_lhs=In q" "redex=In q" "rule_rhs=sF6" "replacement=sF6" "rule_lhs=In q" "rule_rhs=sF6" "redex=In q" "replacement=sF6" "parent_0_substitution=[]" "parent_0_substituted_clause=cnf(u450_subst,axiom,\n    (((c_In @ q @ omega)) = $true)).\n" "parent_0_substituted_clause_db_indices=cnf(u450_subst,axiom,\n    (((c_In @ q @ omega)) = $true)).\n" "parent_1_substitution=[]" "parent_1_substituted_clause=cnf(u428_subst,axiom,\n    (((c_In @ q)) = sF6)).\n" "parent_1_substituted_clause_db_indices=cnf(u428_subst,axiom,\n    (((c_In @ q)) = sF6)).\n"))
  (step_proposition "u523" "vampire_or (vampire_eq_prop (vampire_true) (sF7)) ((split_5) -> vampire_false)")
  (step_extra "u523" "split_dependency" ("dependency_0_split_level=8" "dependency_0_split_var=5" "dependency_0_split_positive=1" "dependency_0_component_clause=vampire_or (vampire_eq_prop (In q omega) (vampire_true)) ((split_5) -> vampire_false)" "dependency_0_component_clause_variable_sort_count=0" "dependency_0_component_clause_db_sort_count=0" "dependency_count=1"))
  (step_extra "u523" "two_literal_rewrite" ("selected=($true = ((sF6 @ omega)))" "other=(((sF6 @ omega)) = sF7)" "selected_parent_index=0" "selected_literal_index=0" "selected_parent_unit=510" "selected_substituted=($true = ((sF6 @ omega)))" "selected_substituted_db_indices=($true = ((sF6 @ omega)))" "selected_substituted_proposition=vampire_eq_prop (vampire_true) (sF6 omega)" "other_parent_index=1" "other_literal_index=0" "other_parent_unit=429" "other_substituted=(((sF6 @ omega)) = sF7)" "other_substituted_db_indices=(((sF6 @ omega)) = sF7)" "other_substituted_proposition=vampire_eq_prop (sF6 omega) (sF7)" "lhs=sF6 @ omega" "target=sF6 @ omega" "lhs_term=sF6 omega" "target_term=sF6 omega" "lhs_sort=prop" "target_sort=prop" "parent_0_substitution=[0 -> X0]" "parent_0_substituted_clause=cnf(u510_subst,axiom,\n    ($true = ((sF6 @ omega)))).\n" "parent_0_substituted_clause_db_indices=cnf(u510_subst,axiom,\n    ($true = ((sF6 @ omega)))).\n" "parent_1_substitution=[0 -> X1]" "parent_1_substituted_clause=cnf(u429_subst,axiom,\n    (((sF6 @ omega)) = sF7)).\n" "parent_1_substituted_clause_db_indices=cnf(u429_subst,axiom,\n    (((sF6 @ omega)) = sF7)).\n"))
  (step_proposition "u529" "(split_5) -> vampire_false")
  (step_extra "u529" "split_dependency" ("dependency_0_split_level=8" "dependency_0_split_var=5" "dependency_0_split_positive=1" "dependency_0_component_clause=vampire_or (vampire_eq_prop (In q omega) (vampire_true)) ((split_5) -> vampire_false)" "dependency_0_component_clause_variable_sort_count=0" "dependency_0_component_clause_db_sort_count=0" "dependency_count=1"))
  (step_extra "u529" "literal" ("selected=($true = sF7)" "selected_parent_index=0" "selected_literal_index=0" "selected_parent_unit=523" "selected_substitution_source=sat_subsumption" "selected_substitution=[]" "selected_substituted=($true = sF7)" "selected_substituted_db_indices=($true = sF7)" "selected_substituted_proposition=vampire_eq_prop (vampire_true) (sF7)"))
  (step_proposition "u530" "(split_5) -> vampire_false")
  (step_extra "u530" "raw" ("sat_clause_recorded"))
  (step_proposition "u531" "vampire_false")
  (symbol_declaration "Variable In:set->set->prop.")
  (symbol_declaration "Variable omega:set.")
  (symbol_declaration "Variable q:set.")
  (symbol_declaration "Variable f__true:prop.")
  (symbol_declaration "Variable sF6:set->prop.")
  (symbol_declaration "Variable sF7:prop.")
  (formula_input "u82" (source axiom "c_Hq") (pos (AP (AP (TMH "In") (TMH "q")) (TMH "omega"))))
  (formula_input "u91" (source conjecture "conj_c__2Fproject_2Ftmp_2Fmegalodon3_5Fsource_5Flinked_5Fcorpus_5F250_2Fhammer_5F10805_5F119") (pos (AP (AP (TMH "In") (TMH "q")) (TMH "omega"))))
  (formula_term_input "u92" (source negated_conjecture "conj_c__2Fproject_2Ftmp_2Fmegalodon3_5Fsource_5Flinked_5Fcorpus_5F250_2Fhammer_5F10805_5F119") (formula (IMP (AP (AP (TMH "In") (TMH "q")) (TMH "omega")) (TMH "vampire_false"))))
  (rectify_formula "u249" (parent "u82") (result (formula (AP (AP (TMH "In") (TMH "q")) (TMH "omega")))))
  (fool_bool "u250" (parent "u249") (result (pos (AP (AP (TMH "=") (AP (AP (TMH "In") (TMH "q")) (TMH "omega"))) (TMH "f__true")))))
  (rectify_formula "u267" (parent "u92") (result (formula (IMP (AP (AP (TMH "In") (TMH "q")) (TMH "omega")) (TMH "vampire_false")))))
  (fool_bool "u268" (parent "u267") (result (neg (AP (AP (TMH "=") (AP (AP (TMH "In") (TMH "q")) (TMH "omega"))) (TMH "f__true")))))
  (formula_copy "u270" (parent "u268") (result (neg (AP (AP (TMH "=") (AP (AP (TMH "In") (TMH "q")) (TMH "omega"))) (TMH "f__true")))))
  (cnf_literal "u397" (parent "u250") (result (clause (pos (AP (AP (TMH "=") (AP (AP (TMH "In") (TMH "q")) (TMH "omega"))) (TMH "f__true"))))))
  (cnf_literal "u414" (parent "u270") (result (clause (neg (AP (AP (TMH "=") (AP (AP (TMH "In") (TMH "q")) (TMH "omega"))) (TMH "f__true"))))))
  (definition_input "u428" (result (clause (pos (AP (AP (TMH "=") (AP (TMH "In") (TMH "q"))) (TMH "sF6"))))))
  (definition_input "u429" (result (clause (pos (AP (AP (TMH "=") (AP (TMH "sF6") (TMH "omega"))) (TMH "sF7"))))))
  (paramodulate "u430_paramodulate0" (equality "u428" 0) (target "u414" 0) (position 0 1 0) (from (AP (TMH "In") (TMH "q"))) (to (TMH "sF6")) (result (clause (neg (AP (AP (TMH "=") (TMH "f__true")) (AP (TMH "sF6") (TMH "omega")))))))
  (paramodulate "u430" (equality "u429" 0) (target "u430_paramodulate0" 0) (position 1) (from (AP (TMH "sF6") (TMH "omega"))) (to (TMH "sF7")) (result (clause (neg (AP (AP (TMH "=") (TMH "f__true")) (TMH "sF7"))))))
  (avatar_component "u450" (result (clause (pos (AP (AP (TMH "=") (AP (AP (TMH "In") (TMH "q")) (TMH "omega"))) (TMH "f__true"))) (neg (TMH "split_5")))))
  (paramodulate "u510" (equality "u428" 0) (target "u450" 0) (position 0 1 0) (from (AP (TMH "In") (TMH "q"))) (to (TMH "sF6")) (result (clause (pos (AP (AP (TMH "=") (TMH "f__true")) (AP (TMH "sF6") (TMH "omega")))) (neg (TMH "split_5")))))
  (substitute "u523_subst0" (parent "u510") (subst) (result (clause (pos (AP (AP (TMH "=") (TMH "f__true")) (AP (TMH "sF6") (TMH "omega")))) (neg (TMH "split_5")))))
  (substitute "u523_subst1" (parent "u429") (subst ("X0" (TMH "X1"))) (result (clause (pos (AP (AP (TMH "=") (AP (TMH "sF6") (TMH "omega"))) (TMH "sF7"))))))
  (paramodulate "u523" (equality "u523_subst1" 0) (target "u523_subst0" 0) (position 1) (from (AP (TMH "sF6") (TMH "omega"))) (to (TMH "sF7")) (result (clause (pos (AP (AP (TMH "=") (TMH "f__true")) (TMH "sF7"))) (neg (TMH "split_5")))))
  (resolve "u529" (parents "u523" "u430") (pivot 0 0) (result (clause (neg (TMH "split_5")))))
  (avatar_split "u530" (parents "u529") (result (clause (neg (TMH "split_5")))))
  (avatar_split "u460" (parents "u397") (result (clause (pos (TMH "split_5")))))
  (avatar_refutation "u531" (parents "u530" "u460") (sat_clauses (sat_clause (lit 5 false)) (sat_clause (lit 5 true))) (sat_proof (sat_input 7 (sat_clause (lit 5 true))) (sat_input 22 (sat_clause (lit 5 false))) (sat_rup 28 (parents 7 22) (result (sat_clause)))) (result (clause)))
)
