(certificate vampire-megalodon 1
  (problem "vampire-native-certificate")
  (step_proposition "u79" "Empty = SNoLev x")
  (step_extra "u79" "raw" ("number=1"))
  (step_proposition "u82" "Empty = SNoLev x")
  (step_proposition "u83" "(Empty = SNoLev x) -> vampire_false")
  (step_proposition "u241" "(Empty = SNoLev x) -> vampire_false")
  (step_extra "u241" "normal_form" ("rule=flattening" "source=(Empty = SNoLev x) -> vampire_false" "target=(Empty = SNoLev x) -> vampire_false"))
  (step_extra "u241" "raw" ("number=1"))
  (step_proposition "u330" "Empty = SNoLev x")
  (step_extra "u330" "cnf" ("rule=cnf transformation" "parent_unit=79" "parent_kind=formula" "source=Empty = SNoLev x" "source_proposition=Empty = SNoLev x" "target=Empty = SNoLev x" "target_proposition=Empty = SNoLev x" "target_clause=[{\"polarity\":true,\"atom\":{\"eq\":[{\"const\":\"Empty\"},{\"apply\":[{\"const\":\"SNoLev\"},{\"const\":\"x\"}]}]}}]" "target_literal_count=1" "target_literal_0=Empty = SNoLev x" "parent_clause_count=1" "clause_parent_unit=79" "clause_index=0" "clause_count=1" "target_variable_sort_count=0"))
  (step_extra "u330" "raw" ("parent=79,index=0,count=1"))
  (step_proposition "u333" "(Empty = SNoLev x) -> vampire_false")
  (step_extra "u333" "cnf" ("rule=cnf transformation" "parent_unit=241" "parent_kind=formula" "source=(Empty = SNoLev x) -> vampire_false" "source_proposition=(Empty = SNoLev x) -> vampire_false" "target=(Empty = SNoLev x) -> vampire_false" "target_proposition=(Empty = SNoLev x) -> vampire_false" "target_clause=[{\"polarity\":false,\"atom\":{\"eq\":[{\"const\":\"Empty\"},{\"apply\":[{\"const\":\"SNoLev\"},{\"const\":\"x\"}]}]}}]" "target_literal_count=1" "target_literal_0=(Empty = SNoLev x) -> vampire_false" "parent_clause_count=1" "clause_parent_unit=241" "clause_index=0" "clause_count=1" "target_variable_sort_count=0"))
  (step_extra "u333" "raw" ("parent=241,index=0,count=1"))
  (step_proposition "u338" "SNoLev x = sF0")
  (step_extra "u338" "function_definition" ("introduced_symbol=sF0" "sort=set" "equality_sort=set" "lhs=SNoLev x" "rhs=sF0" "proposition=SNoLev x = sF0"))
  (step_proposition "u339" "(Empty = sF0) -> vampire_false")
  (step_extra "u339" "definition_rewrite" ("rule=definition folding" "target=(Empty = sF0) -> vampire_false" "parent_0=(Empty = SNoLev x) -> vampire_false" "source=(Empty = SNoLev x) -> vampire_false" "parent_1=SNoLev x = sF0" "definition=SNoLev x = sF0" "fold_step_count=1" "fold_step_0_lhs=SNoLev x" "fold_step_0_rhs=sF0" "fold_step_0_literal=0" "fold_step_0_position=1"))
  (step_extra "u339" "raw" ("steps=1,step0=(c_SNoLev @ x -> sF0)@0:1"))
  (step_proposition "u345" "Empty = sF0")
  (step_extra "u345" "rewrite" ("lhs=c_SNoLev @ x" "target=c_SNoLev @ x" "rule_lhs=SNoLev x" "redex=SNoLev x" "rule_rhs=Empty" "replacement=Empty" "rule_lhs=SNoLev x" "rule_rhs=Empty" "redex=SNoLev x" "replacement=Empty" "parent_0_substitution=[]" "parent_0_substituted_clause=cnf(u338_subst,axiom,\n    (((c_SNoLev @ x)) = sF0)).\n" "parent_0_substituted_clause_db_indices=cnf(u338_subst,axiom,\n    (((c_SNoLev @ x)) = sF0)).\n" "parent_1_substitution=[]" "parent_1_substituted_clause=cnf(u330_subst,axiom,\n    (c_Empty = ((c_SNoLev @ x)))).\n" "parent_1_substituted_clause_db_indices=cnf(u330_subst,axiom,\n    (c_Empty = ((c_SNoLev @ x)))).\n"))
  (step_proposition "u362" "vampire_false")
  (step_extra "u362" "literal" ("selected=(c_Empty = sF0)" "selected_parent_index=0" "selected_literal_index=0" "selected_parent_unit=345" "selected_substitution_source=sat_subsumption" "selected_substitution=[]" "selected_substituted=(c_Empty = sF0)" "selected_substituted_db_indices=(c_Empty = sF0)" "selected_substituted_proposition=Empty = sF0"))
  (symbol_declaration "Variable Empty:set.")
  (symbol_declaration "Variable SNoLev:set->set.")
  (symbol_declaration "Variable x:set.")
  (symbol_declaration "Variable sF0:set.")
  (formula_input "u79" (source axiom "c_Hx2") (pos (AP (AP (TMH "=") (TMH "Empty")) (AP (TMH "SNoLev") (TMH "x")))))
  (formula_input "u82" (source conjecture "conj_c__2Fproject_2Ftmp_2Fsource_5Flinked_5Fstrict_5F100_5Fcorpus_5Ffresh_5F041947_2Fhammer_5F11572_5F88") (pos (AP (AP (TMH "=") (TMH "Empty")) (AP (TMH "SNoLev") (TMH "x")))))
  (formula_term_input "u83" (source negated_conjecture "conj_c__2Fproject_2Ftmp_2Fsource_5Flinked_5Fstrict_5F100_5Fcorpus_5Ffresh_5F041947_2Fhammer_5F11572_5F88") (formula (IMP (AP (AP (TMH "=") (TMH "Empty")) (AP (TMH "SNoLev") (TMH "x"))) (TMH "vampire_false"))))
  (formula_copy "u241" (parent "u83") (result (neg (AP (AP (TMH "=") (TMH "Empty")) (AP (TMH "SNoLev") (TMH "x"))))))
  (cnf_literal "u330" (parent "u79") (result (clause (pos (AP (AP (TMH "=") (TMH "Empty")) (AP (TMH "SNoLev") (TMH "x")))))))
  (cnf_literal "u333" (parent "u241") (result (clause (neg (AP (AP (TMH "=") (TMH "Empty")) (AP (TMH "SNoLev") (TMH "x")))))))
  (definition_input "u338" (result (clause (pos (AP (AP (TMH "=") (AP (TMH "SNoLev") (TMH "x"))) (TMH "sF0"))))))
  (paramodulate "u339" (equality "u338" 0) (target "u333" 0) (position 1) (from (AP (TMH "SNoLev") (TMH "x"))) (to (TMH "sF0")) (result (clause (neg (AP (AP (TMH "=") (TMH "Empty")) (TMH "sF0"))))))
  (equality_symmetry "u345_symmetry" (parent "u330") (literal 0) (result (clause (pos (AP (AP (TMH "=") (AP (TMH "SNoLev") (TMH "x"))) (TMH "Empty"))))))
  (paramodulate "u345" (equality "u345_symmetry" 0) (target "u338" 0) (position 0 1) (from (AP (TMH "SNoLev") (TMH "x"))) (to (TMH "Empty")) (result (clause (pos (AP (AP (TMH "=") (TMH "Empty")) (TMH "sF0"))))))
  (resolve "u362" (parents "u345" "u339") (pivot 0 0) (result (clause)))
)
