(certificate vampire-megalodon 1
  (problem "vampire-native-certificate")
  (step_proposition "u1" "vampire_or (q) (p)")
  (step_proposition "u2" "(p) -> vampire_false")
  (step_proposition "u3" "(q) -> vampire_false")
  (step_proposition "u4" "p")
  (step_extra "u4" "two_literal" ("selected=q" "other=~q" "selected_parent_index=0" "selected_literal_index=0" "selected_parent_unit=1" "selected_substituted=q" "selected_substituted_db_indices=q" "selected_substituted_proposition=q" "other_parent_index=1" "other_literal_index=0" "other_parent_unit=3" "other_substituted=~q" "other_substituted_db_indices=~q" "other_substituted_proposition=(q) -> vampire_false" "parent_0_substitution=[0 -> X0]" "parent_0_substituted_clause=cnf(u1_subst,axiom,\n    q | p).\n" "parent_0_substituted_clause_db_indices=cnf(u1_subst,axiom,\n    q | p).\n" "parent_1_substitution=[0 -> X1]" "parent_1_substituted_clause=cnf(u3_subst,axiom,\n    ~q).\n" "parent_1_substituted_clause_db_indices=cnf(u3_subst,axiom,\n    ~q).\n"))
  (step_proposition "u5" "vampire_false")
  (step_extra "u5" "two_literal" ("selected=p" "other=~p" "selected_parent_index=0" "selected_literal_index=0" "selected_parent_unit=4" "selected_substituted=p" "selected_substituted_db_indices=p" "selected_substituted_proposition=p" "other_parent_index=1" "other_literal_index=0" "other_parent_unit=2" "other_substituted=~p" "other_substituted_db_indices=~p" "other_substituted_proposition=(p) -> vampire_false" "parent_0_substitution=[0 -> X0]" "parent_0_substituted_clause=cnf(u4_subst,axiom,\n    p).\n" "parent_0_substituted_clause_db_indices=cnf(u4_subst,axiom,\n    p).\n" "parent_1_substitution=[0 -> X1]" "parent_1_substituted_clause=cnf(u2_subst,axiom,\n    ~p).\n" "parent_1_substituted_clause_db_indices=cnf(u2_subst,axiom,\n    ~p).\n"))
  (symbol_declaration "Variable p:prop.")
  (symbol_declaration "Variable q:prop.")
  (input "u1" (source axiom "a1") (clause (pos (TMH "q")) (pos (TMH "p"))))
  (input "u2" (source axiom "a2") (clause (neg (TMH "p"))))
  (input "u3" (source axiom "a3") (clause (neg (TMH "q"))))
  (resolve "u4" (parents "u1" "u3") (pivot 0 0) (result (clause (pos (TMH "p")))))
  (resolve "u5" (parents "u4" "u2") (pivot 0 0) (result (clause)))
)
