#!/usr/bin/env bash
set -euo pipefail

ROOT=${ROOT:-"$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"}
TMPDIR=${TMPDIR:-/project/tmp}
export TMPDIR

PROBLEMS_FILE=${PROBLEMS_FILE:-"$ROOT/tests/vampire_certificate/known_solvable_strict_100.list"}
LIMIT=${LIMIT:-100}
JOBS=${JOBS:-20}
MIN_PASS=${MIN_PASS:-100}
VAMPIRE_SECONDS=${VAMPIRE_SECONDS:-10}
WALL_SECONDS=${WALL_SECONDS:-13}
STRICT_CERT_V1=${STRICT_CERT_V1:-1}
CHECK_SOURCE_MAP=${CHECK_SOURCE_MAP:-1}
AUDIT_NATIVE_PRIMITIVES=${AUDIT_NATIVE_PRIMITIVES:-1}
AUDIT_KERNEL_V1_METADATA=${AUDIT_KERNEL_V1_METADATA:-1}
WORK_DIR=${WORK_DIR:-"$TMPDIR/native_live_known_solvable_strict_100"}

export ROOT PROBLEMS_FILE LIMIT JOBS MIN_PASS VAMPIRE_SECONDS WALL_SECONDS
export STRICT_CERT_V1 CHECK_SOURCE_MAP AUDIT_NATIVE_PRIMITIVES AUDIT_KERNEL_V1_METADATA WORK_DIR

"$ROOT/tests/vampire_certificate/run_native_live_parallel.sh"
